PLUGIN_NAME=		siproxd
PLUGIN_VERSION=		0.2
PLUGIN_COMMENT=		Siproxd is a proxy daemon for the SIP protocol
PLUGIN_DEPENDS=		siproxd
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
