PLUGIN_NAME=		siproxd
PLUGIN_VERSION=		1.3
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		Siproxd is a proxy daemon for the SIP protocol
PLUGIN_DEPENDS=		siproxd
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
