[start]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php start
parameters:
type:script
message:starting nebula

[stop]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php stop
parameters:
type:script
message:stopping nebula

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php restart
parameters:
type:script
message:restarting nebula

[reconfigure]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php apply
parameters:
type:script
message:reconfigure nebula

[status]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php status
parameters:
type:script_output
message:nebula status

[pki_generate_ca]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/pki.php generate-ca
parameters:%s
type:script_output
message:nebula generate ca

[pki_sign_cert]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/pki.php sign-cert
parameters:%s
type:script_output
message:nebula sign cert

[pki_print_cert]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/pki.php print-cert
parameters:%s
type:script_output
message:nebula print cert

[restart_instance]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php restart
parameters:%s
type:script_output
message:restart nebula instance

[status_instance]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php status
parameters:%s
type:script_output
message:nebula instance status

[diag_instance]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php diag
parameters:%s
type:script_output
message:nebula instance diagnostics

[peers_instance]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php peers
parameters:%s
type:script_output
message:nebula instance peers

[debug_instance]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php debug
parameters:%s %s %s %s
type:script_output
message:nebula instance debug

[snapshot]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php snapshot
type:script_output
message:nebula status snapshot

[peers_all]
command:/usr/local/opnsense/scripts/OPNsense/Nebula/setup.php peers_all
type:script_output
message:nebula all peers
