PLUGIN_NAME=		zabbix-agent
PLUGIN_VERSION=		1.19
PLUGIN_COMMENT=		Zabbix monitoring agent
PLUGIN_MAINTAINER=	opnsense@moov.de
PLUGIN_VARIANTS=	zabbix7 zabbix74 zabbix6

zabbix7_NAME=		zabbix7-agent
zabbix7_DEPENDS=	zabbix7-agent

zabbix74_NAME=		zabbix74-agent
zabbix74_DEPENDS=	zabbix74-agent

zabbix6_NAME=		zabbix6-agent
zabbix6_DEPENDS=	zabbix6-agent

.include "../../Mk/plugins.mk"
