PLUGIN_NAME=        zabbix-agent
PLUGIN_VERSION=     1.0
PLUGIN_COMMENT=     Enterprise-class open source distributed monitoring agent
PLUGIN_DEPENDS=     zabbix32-agent
PLUGIN_MAINTAINER=  opnsense@moov.de

.include "../../Mk/plugins.mk"
