PLUGIN_NAME=		nextcloud-backup
PLUGIN_VERSION=		0.1
PLUGIN_DEVEL=		yes
PLUGIN_COMMENT=		Track config changes using NextCloud
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
