PLUGIN_NAME=		nextcloud-backup
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Track config changes using NextCloud
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
