PLUGIN_NAME=		frr
PLUGIN_VERSION=		1.31
PLUGIN_COMMENT=		The FRRouting Protocol Suite
PLUGIN_DEPENDS=		frr7
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
