PLUGIN_NAME=		frr
PLUGIN_VERSION=		1.3
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		The FRRouting Protocol Suite
PLUGIN_DEPENDS=		frr3 ruby
PLUGIN_CONFLICTS=	quagga
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
