PLUGIN_NAME=		frr
PLUGIN_VERSION=		1.6
PLUGIN_COMMENT=		The FRRouting Protocol Suite
PLUGIN_DEPENDS=		frr5 ruby
PLUGIN_CONFLICTS=	quagga
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
