PLUGIN_NAME=		boot-delay
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Apply a persistent 10 second boot delay
PLUGIN_MAINTAINER=	franco@opnsense.org
PLUGIN_OBSOLETE=	Use System: Tunables: name "kern.cam.boot_delay" value "10000"

.include "../../Mk/plugins.mk"
