PLUGIN_NAME=		caddy
PLUGIN_VERSION=		1.7.0
PLUGIN_DEPENDS=		caddy-custom
PLUGIN_COMMENT=		Reverse Proxy with Automatic HTTPS, Dynamic DNS and Layer4 Streaming
PLUGIN_MAINTAINER=	cedrik@pischem.com

.include "../../Mk/plugins.mk"
