PLUGIN_NAME=		caddy
PLUGIN_VERSION=		1.9.0
PLUGIN_DEPENDS=		caddy-custom xcaddy go124
PLUGIN_COMMENT=		Modern Reverse Proxy with Automatic HTTPS, Dynamic DNS and Layer4 Routing
PLUGIN_MAINTAINER=	cedrik@pischem.com

.include "../../Mk/plugins.mk"
