PLUGIN_NAME=		caddy
PLUGIN_VERSION=		1.8.2
PLUGIN_DEPENDS=		caddy-custom
PLUGIN_COMMENT=		Modern Reverse Proxy with Automatic HTTPS, Dynamic DNS and Layer4 Routing
PLUGIN_MAINTAINER=	cedrik@pischem.com

.include "../../Mk/plugins.mk"
