PLUGIN_NAME=        sslh
PLUGIN_VERSION=     0.1
PLUGIN_DEVEL=       yes
PLUGIN_COMMENT=     sslh configuration front-end
PLUGIN_DEPENDS=     sslh
PLUGIN_MAINTAINER=  agh1467@protonmail.com

.include "../../Mk/plugins.mk"
