PLUGIN_NAME=		sslh
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		sslh configuration front-end
PLUGIN_DEPENDS=		sslh
PLUGIN_MAINTAINER=	agh1467@protonmail.com

.include "../../Mk/plugins.mk"
