PLUGIN_NAME=		sslh
PLUGIN_VERSION=		1.21c
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		sslh configuration front-end
PLUGIN_DEPENDS=		sslh
PLUGIN_MAINTAINER=	7823088+agh1467@users.noreply.github.com

.include "../../Mk/plugins.mk"
