PLUGIN_NAME=		web-proxy-useracl
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Group and user ACL for the web proxy
PLUGIN_MAINTAINER=	kekek2@ya.ru
PLUGIN_WWW=		http://smart-soft.ru

.include "../../Mk/plugins.mk"
