PLUGIN_NAME=		web-proxy-useracl
PLUGIN_VERSION=		1.1
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		Group and user ACL for the web proxy
PLUGIN_MAINTAINER=	kekek2@ya.ru
PLUGIN_WWW=		https://smart-soft.ru

.include "../../Mk/plugins.mk"
