PLUGIN_NAME=		web-proxy-useracl
PLUGIN_VERSION=		0.0.1
PLUGIN_COMMENT=		Group & User Squid ACL
PLUGIN_DEPENDS=
PLUGIN_MAINTAINER=	kekek2@ya.ru
PLUGIN_WWW=			http://smart-soft.ru
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
