PLUGIN_NAME=		zabbix-proxy4
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Zabbix Proxy enables decentralized monitoring
PLUGIN_DEPENDS=		zabbix4-proxy
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
