PLUGIN_NAME=		intel-em
PLUGIN_VERSION=		1.2
PLUGIN_COMMENT=		Intel Gigabit Base Driver for em(4) and lem(4)
PLUGIN_DEPENDS=		intel-em-kmod
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
