PLUGIN_NAME=		intel-em
PLUGIN_VERSION=		1.1
PLUGIN_COMMENT=		Intel Gigabit Base Driver wrapper (requires reboot after install/deinstall)
PLUGIN_DEPENDS=		intel-em-kmod
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
