PLUGIN_NAME=		quagga
PLUGIN_VERSION=		0.0.3
PLUGIN_COMMENT=		Quagga Routing Suite
PLUGIN_DEPENDS=		quagga
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
