PLUGIN_NAME=		quagga
PLUGIN_VERSION=		1.4.4
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		End of life, superseded by FRR plugin
PLUGIN_DEPENDS=		quagga ruby
PLUGIN_CONFLICTS=	frr
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
