#!/bin/sh
#
# $FreeBSD$
#
# PROVIDE: opnsense-wireguard
# REQUIRE: SERVERS
# KEYWORD: shutdown
#

. /etc/rc.subr

name=opnsense_wireguard

stop_cmd=opnsense_wireguard_stop
start_cmd=opnsense_wireguard_start
status_cmd=opnsense_wireguard_status
rcvar=opnsense_wireguard_enable

load_rc_config opnsense-wireguard
command=/usr/local/bin/wg-quick

[ -z "$opnsense_wireguard_enable" ] && opnsense_wireguard_enable="NO"

# stop wireguard
opnsense_wireguard_stop()
{
    echo "stopping wireguard"
    for STARTER in ${opnsense_wireguard_config}; do
        $command down $STARTER
    done
    sleep 5
}

# start wireguard
opnsense_wireguard_start()
{
    echo "starting wireguard"
    for STARTER in ${opnsense_wireguard_config}; do
        $command up $STARTER
	ifconfig $STARTER group wireguard
    done
}

run_rc_command $1
