PLUGIN_NAME=		theme-flexcolor
PLUGIN_VERSION=		1.0
- PLUGIN_REVISION=	1
PLUGIN_COMMENT=		OPNsense theme with 3 different color schemes (black as default, light and darklight)
PLUGIN_MAINTAINER=	iengels@web.de
- PLUGIN_WWW=		-
PLUGIN_NO_ABI=		yes

.include "../../Mk/plugins.mk"
