PLUGIN_NAME=		theme-flexcolor
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Theme with 3 different color schemes: black as default, light and dark-light
PLUGIN_MAINTAINER=	iengels@web.de
PLUGIN_NO_ABI=		yes

.include "../../Mk/plugins.mk"
