PLUGIN_NAME=		theme-flexcolor
PLUGIN_VERSION=		1.01
PLUGIN_COMMENT=		OPNsense theme with 3 different color schemes (black as default, light and darklight)
PLUGIN_MAINTAINER=	iengels@web.de
PLUGIN_NO_ABI=		yes

.include "../../Mk/plugins.mk"
