PLUGIN_NAME=		firewall
PLUGIN_VERSION=		1.4
PLUGIN_REVISION=	3
PLUGIN_COMMENT=		Firewall API supplemental package
PLUGIN_OBSOLETE=	yes
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
