PLUGIN_NAME=		web-proxy-sso
PLUGIN_VERSION=		0.3
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Add SSO Active Directory to use in Proxy
PLUGIN_DEPENDS=		msktutil
PLUGIN_MAINTAINER=	gitdevmod@github.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
