PLUGIN_NAME=		web-proxy-sso
PLUGIN_VERSION=		0.3
PLUGIN_PRIVATE=		yes
PLUGIN_COMMENT=		Add SSO Active Directory to use in Proxy
PLUGIN_DEPENDS=		msktutil
PLUGIN_MAINTAINER=	gitdevmod@github.com

.include "../../Mk/plugins.mk"
