PLUGIN_NAME=          rspamd
PLUGIN_VERSION=       0.1
PLUGIN_COMMENT=       Package to configure rspamd to protect your network from malware and spam
PLUGIN_DEPENDS=       rspamd os-clamav
PLUGIN_MAINTAINER=    franz.fabian.94@gmail.com
PLUGIN_DEVEL=         YES

.include "../../Mk/plugins.mk"
