PLUGIN_NAME=		nginx
PLUGIN_VERSION=		1.34
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Nginx HTTP server and reverse proxy
PLUGIN_DEPENDS=		nginx
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
