PLUGIN_NAME=          nginx
PLUGIN_VERSION=       0.2
PLUGIN_COMMENT=       Nginx HTTP server and reverse proxy
PLUGIN_DEPENDS=       nginx
PLUGIN_MAINTAINER=    franz.fabian.94@gmail.com
PLUGIN_DEVEL=         yes

.include "../../Mk/plugins.mk"
