#!/bin/sh
#
# PROVIDE: opncaddy
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Wrapper script for Caddy to execute a setup script before starting.

. /etc/rc.subr

name="opncaddy"
rcvar=opncaddy_enable

load_rc_config $name

: ${opncaddy_enable:=NO}

# Define paths
caddy_service="/usr/local/etc/rc.d/caddy"  # Original Caddy service script
caddy_setup_script="/usr/local/opnsense/scripts/Pischem/Caddy/setup.sh"  # Path to your setup script

start_precmd="opncaddy_precmd"

opncaddy_precmd()
{
    # Call the setup script before starting the service
    sh ${caddy_setup_script}
}

# Overriding the default start command to include our precmd
opncaddy_start()
{
    opncaddy_precmd && ${caddy_service} onestart
}

# Overriding the default stop command
opncaddy_stop()
{
    ${caddy_service} onestop
}

# Overriding the default restart command
opncaddy_restart()
{
    opncaddy_precmd && ${caddy_service} onerestart
}

# Service command overrides
start_cmd="opncaddy_start"
stop_cmd="opncaddy_stop"
restart_cmd="opncaddy_restart"

run_rc_command "$1"

