PLUGIN_NAME=		git-backup
PLUGIN_VERSION=		1.1
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		Track config changes using git
PLUGIN_DEPENDS=		git
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
