PLUGIN_NAME=		git-backup
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Track config changes using git
PLUGIN_DEPENDS=		git
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
