PLUGIN_NAME=          iperf3
PLUGIN_VERSION=       0.0.1
PLUGIN_COMMENT=       iperf3 connection speed tester
PLUGIN_DEPENDS=       iperf3 ruby
PLUGIN_MAINTAINER=    franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
