PLUGIN_NAME=		ndproxy
PLUGIN_VERSION=		1.1
PLUGIN_DEPENDS=		ndproxy
PLUGIN_COMMENT=		End of life: please use os-ndp-proxy-go
PLUGIN_MAINTAINER=	cedrik@pischem.com
PLUGIN_OBSOLETE=	yes

.include "../../Mk/plugins.mk"
