PLUGIN_NAME=		openconnect
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		OpenConnect Client
PLUGIN_DEPENDS=		openconnect
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=       yes

.include "../../Mk/plugins.mk"
