PLUGIN_NAME=		openconnect
PLUGIN_VERSION=		1.4.2
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		OpenConnect Client
PLUGIN_DEPENDS=		openconnect
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
