PLUGIN_NAME=       mdns-repeater
PLUGIN_VERSION=    1.0
PLUGIN_COMMENT=    Proxy multicast DNS between networks
PLUGIN_MAINTAINER= franz.fabian.94@gmail.com
PLUGIN_DEPENDS=    mdns-repeater
PLUGIN_DEVEL=      yes

.include "../../Mk/plugins.mk"
