PLUGIN_NAME=		mdns-repeater
PLUGIN_VERSION=		1.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Proxy multicast DNS between networks
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com
PLUGIN_DEPENDS=		mdns-repeater

.include "../../Mk/plugins.mk"
