PLUGIN_NAME=		checkip
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	0
PLUGIN_COMMENT=		Use alternate services to get current IP address (custom DynDNS and RFC2136).
PLUGIN_MAINTAINER=	NOYB at github

.include "../../Mk/plugins.mk"
