PLUGIN_NAME=		pppoe
PLUGIN_VERSION=		1.7
PLUGIN_REVISION=	1
PLUGIN_DEPENDS=		clog mpd5
PLUGIN_COMMENT=		PPPoE server based on MPD5
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
