PLUGIN_NAME=		pppoe
PLUGIN_PRIVATE=		yes
PLUGIN_VERSION=		0.4
PLUGIN_DEPENDS=		clog mpd5
PLUGIN_COMMENT=		PPPoE server based on MPD5
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
