PLUGIN_NAME=		intel-em-kmod
PLUGIN_VERSION=		1.0.1
PLUGIN_COMMENT=		intel-em-kmod wrapper (please reboot after install/deinstall)
PLUGIN_DEPENDS=		intel-em-kmod
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
