PLUGIN_NAME=		igmpproxy
PLUGIN_VERSION=		0.1
PLUGIN_PRIVATE=		yes
PLUGIN_DEPENDS=		igmpproxy
PLUGIN_COMMENT=		IGMP-Proxy Service
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
