PLUGIN_NAME=		dmidecode
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Display hardware information on the dashboard
PLUGIN_DEPENDS=		dmidecode
PLUGIN_MAINTAINER=	evbevz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
