PLUGIN_NAME=		dmidecode
PLUGIN_VERSION=		1.2
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Display hardware information on the dashboard
PLUGIN_DEPENDS=		dmidecode
PLUGIN_MAINTAINER=	evbevz@gmail.com
PLUGIN_WWW=		https://smart-soft.ru

.include "../../Mk/plugins.mk"
