PLUGIN_NAME=		cpu-microcode-amd
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		AMD CPU microcode updates
PLUGIN_DEPENDS=		cpu-microcode-amd x86info
PLUGIN_CONFLICTS=	cpu-microcode-intel
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
