PLUGIN_NAME=		hclouddns
PLUGIN_VERSION=		2.0.0
PLUGIN_COMMENT=		Hetzner Cloud DNS Management with Multi-Zone and Failover
PLUGIN_MAINTAINER=	info@arcan-it.de
PLUGIN_WWW=		https://github.com/ArcanConsulting/os-hclouddns
PLUGIN_DEPENDS=		python311

.include "../../Mk/plugins.mk"
