[start]
command:service avahi-daemon start
parameters:
type:script
message:starting avahi-daemon

[stop]
command:service avahi-daemon stop
parameters:
type:script
message:stopping avahi-daemon

[restart]
command:service avahi-daemon restart
parameters:
type:script
message:restarting avahi-daemon

[status]
command:service avahi-daemon status; true
parameters:
type:script_output
message:requesting avahi-daemon status

[diagnostics]
command:/usr/local/opnsense/scripts/OPNsense/AvahiReflector/status.py
parameters:
type:script_output
message:requesting avahi-daemon diagnostics

[healthcheck]
command:/usr/local/opnsense/scripts/OPNsense/AvahiReflector/avahi_slot_check.sh
parameters:
type:script_output
message:checking avahi-daemon slot health
