PLUGIN_NAME=		netflector
PLUGIN_VERSION=		1.0.d
PLUGIN_DEVEL=		yes
PLUGIN_COMMENT=		Reflect link-local service discovery between interfaces
PLUGIN_MAINTAINER=	sergii@bogomolov.io
PLUGIN_WWW=		https://github.com/netflector/netflector
PLUGIN_DEPENDS=		netflector

.include "../../Mk/plugins.mk"
