PLUGIN_NAME=		netflector
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Reflect link-local service discovery between interfaces
PLUGIN_MAINTAINER=	sergii@bogomolov.io
PLUGIN_WWW=		https://github.com/netflector/netflector
PLUGIN_DEPENDS=		netflector

# PHP and XML only, so one package serves every architecture.
PLUGIN_NO_ABI=		yes

.include "../../Mk/plugins.mk"
