PLUGIN_NAME=		vmware
PLUGIN_VERSION=		1.5
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		VMware tools
PLUGIN_DEPENDS=		open-vm-tools-nox11
PLUGIN_MAINTAINER=	franco@opnsense.org
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
