PLUGIN_NAME=		softether
PLUGIN_VERSION=		0.3
PLUGIN_COMMENT=		Cross-platform Multi-protocol VPN Program
PLUGIN_DEPENDS=		softether
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
