PLUGIN_NAME=		clamav
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Antivirus engine for detecting malicious threats
PLUGIN_DEPENDS=		clamav
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
