PLUGIN_NAME=		clamav
PLUGIN_VERSION=		1.8
PLUGIN_COMMENT=		Antivirus engine for detecting malicious threats
PLUGIN_DEPENDS=		clamav
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
