PLUGIN_NAME=		theme-tukan
PLUGIN_VERSION=		1.27
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		The tukan theme - blue/white
PLUGIN_MAINTAINER=	rene@team-rebellion.net
PLUGIN_NO_ABI=		yes

.include "../../Mk/plugins.mk"
