PLUGIN_NAME=		theme-tukan
PLUGIN_VERSION=		0.3
PLUGIN_REVISION=	0
PLUGIN_COMMENT=		The tukan theme - blue/white
PLUGIN_MAINTAINER=	martin@team-rebellion.net
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
