PLUGIN_NAME=		zabbix4-proxy
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=        1
PLUGIN_COMMENT=		Zabbix Proxy enables decentralized monitoring
PLUGIN_DEPENDS=		zabbix4-proxy
PLUGIN_CONFLICTS=	zabbix-proxy
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
