#!/bin/sh
#
# PROVIDE: flexcolor
# REQUIRE: FILESYSTEMS
#

. /etc/rc.subr

name="flexcolor"
start_cmd="flexcolor_start"
stop_cmd=":"

: ${flexcolor_theme:="black"}

FLEXCOLORDIR="/usr/local/opnsense/www/themes/flexcolor"
SCHEMESDIR="${FLEXCOLORDIR}/build/color_schemes"
TARGETDIR="${FLEXCOLORDIR}/build/css"
DEFAULTCSS="default_scheme.css"

CACHEMARKER="/usr/local/opnsense/www/index.php"

flexcolor_start()
{
	SELECTEDCSS="${SCHEMESDIR}/${flexcolor_theme}/${DEFAULTCSS}"

	if [ -f "${SELECTEDCSS}" ]; then
		cp "${SELECTEDCSS}" "${TARGETDIR}/${DEFAULTCSS}"

		if [ -f "${CACHEMARKER}" ]; then
			touch "${CACHEMARKER}"
		fi
	fi
}

load_rc_config $name
run_rc_command "$1"
