PLUGIN_NAME=		zerotier
PLUGIN_VERSION=		0.1.2
PLUGIN_COMMENT=		Virtual Networks That Just Work
PLUGIN_DEPENDS=		zerotier
PLUGIN_MAINTAINER=	dharrigan@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
