PLUGIN_NAME=		zerotier
PLUGIN_VERSION=		1.3.2
PLUGIN_REVISION=	4
PLUGIN_COMMENT=		Virtual Networks That Just Work
PLUGIN_DEPENDS=		zerotier
PLUGIN_MAINTAINER=	dharrigan@gmail.com

.include "../../Mk/plugins.mk"
