PLUGIN_NAME=		zerotier
PLUGIN_VERSION=		1.4.6
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Virtual Networks That Just Work
PLUGIN_DEPENDS=		zerotier
PLUGIN_MAINTAINER=	dharrigan@gmail.com

.include "../../Mk/plugins.mk"
