PLUGIN_NAME=		wireguard-go
PLUGIN_VERSION=		1.13
PLUGIN_REVISION=	7
PLUGIN_COMMENT=		WireGuard VPN service Go implementation
PLUGIN_CONFLICTS=	wireguard
PLUGIN_OBSOLETE=	yes
PLUGIN_DEPENDS=		wireguard-go wireguard-tools
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
