PLUGIN_NAME=		squid
PLUGIN_VERSION=		1.2
PLUGIN_REVISION=	3
PLUGIN_COMMENT=		Squid is a caching proxy for the web
PLUGIN_DEPENDS=		squid squid-langpack
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
