PLUGIN_NAME=		squid
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Squid is a caching proxy for the web
PLUGIN_DEPENDS=		squid squid-langpack
PLUGIN_TIER=		2
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
