# Please don't modify this file as your changes might be overwritten with
# the next update.
#
{% if helpers.exists('OPNsense.Nut.general.enable') and OPNsense.Nut.general.enable == '1' %}
{%   for ups in helpers.toList('OPNsense.Nut.upses.ups') %}
{%     if ups.enabled == '1' %}
[{{ ups.name }}]
driver={{ ups.driver }}
{%       if ups.driver == 'blazer_ser' %}
user=root
{%       endif %}
{%       if ups.args != '' %}
{%         for args in ups.args.split(',') %}
{{ args }}
{%         endfor %}
{%       endif %}
{%     endif %}
{%   endfor %}
{% endif %}
