PLUGIN_NAME=		smokeping-slave
PLUGIN_VERSION=		0.1
PLUGIN_DEVEL=       YES
PLUGIN_COMMENT=		SmokePing latency logging system (slave components)
PLUGIN_DEPENDS=		smokeping-slave fping
PLUGIN_MAINTAINER=	roman.plessl@prunux.ch

.include "../../Mk/plugins.mk"
