PLUGIN_NAME=		acme-client
PLUGIN_VERSION=		4.0
PLUGIN_COMMENT=		ACME Client
PLUGIN_MAINTAINER=	opnsense@moov.de
PLUGIN_DEPENDS=		acme.sh py${PLUGIN_PYTHON}-dns-lexicon

.include "../../Mk/plugins.mk"
