PLUGIN_NAME=		acme-client
PLUGIN_VERSION=		2.4
PLUGIN_COMMENT=		Let's Encrypt client
PLUGIN_MAINTAINER=	opnsense@moov.de
PLUGIN_DEPENDS=		acme.sh py${PLUGIN_PYTHON}-dns-lexicon

.include "../../Mk/plugins.mk"
