PLUGIN_NAME=		acme-client
PLUGIN_VERSION=		1.27
PLUGIN_COMMENT=		Let's Encrypt client
PLUGIN_MAINTAINER=	opnsense@moov.de
PLUGIN_DEPENDS=		acme.sh py-dns-lexicon${PLUGIN_PYTHON}

.include "../../Mk/plugins.mk"
