PLUGIN_NAME=		l2tp
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	2
PLUGIN_DEPENDS=		clog mpd5
PLUGIN_COMMENT=		L2TP server based on MPD5
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
