PLUGIN_NAME=		l2tp
PLUGIN_PRIVATE=		yes
PLUGIN_VERSION=		0.3
PLUGIN_DEPENDS=		clog mpd5
PLUGIN_COMMENT=		LT2P server based on MPD5
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
