PLUGIN_NAME=		cpu-microcode-intel
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Intel CPU microcode updates
PLUGIN_DEPENDS=		cpu-microcode-intel x86info
PLUGIN_CONFLICTS=	cpu-microcode-amd
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
