# DO NOT EDIT THIS FILE -- OPNsense auto-generated file
{% if helpers.exists('OPNsense.crowdsec.general.agent_enabled') and OPNsense.crowdsec.general.agent_enabled|default("0") == "1" %}
crowdsec_enable="YES"
{% else %}
crowdsec_enable="NO"
{% endif %}
crowdsec_flags="{{ OPNsense.crowdsec.general.crowdsec_flags|default("") }}"
