PLUGIN_NAME=		intrusion-detection-content-at-antiphishing
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Anti-phishing rules
PLUGIN_MAINTAINER=	jul10l1r4@disroot.org
PLUGIN_WWW=		https://julioliraup.github.io/AT/

.include "../../Mk/plugins.mk"
