PLUGIN_NAME=		intrusion-detection-content-julioliraup-antiphishing
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		julioliraup/Antiphishing rulesets for protect against phishing attack. 
PLUGIN_MAINTAINER=	jul10l1r4@disroot.org
PLUGIN_WWW=		https://julioliraup.github.io/AT/

.include "../../Mk/plugins.mk"
