PLUGIN_NAME=		beats
PLUGIN_VERSION=		0.1
PLUGIN_DEVEL=		yes
PLUGIN_COMMENT=		Send logs, network, metrics and heartbeat to Elasticsearch
PLUGIN_DEPENDS=		beats8
PLUGIN_MAINTAINER=	0xThiebaut

.include "../../Mk/plugins.mk"
