PLUGIN_NAME=		beats
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Send logs, network, metrics and heartbeat to Elasticsearch
PLUGIN_DEPENDS=		beats8
PLUGIN_MAINTAINER=	0xThiebaut

.include "../../Mk/plugins.mk"
