PLUGIN_NAME=		udpbroadcastrelay
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	5
PLUGIN_COMMENT=		Control udpbroadcastrelay processes
PLUGIN_DEPENDS=		udpbroadcastrelay
PLUGIN_MAINTAINER=	mjwasley@gmail.com

.include "../../Mk/plugins.mk"
