PLUGIN_NAME=		os-udpbroadcastrelay
PLUGIN_VERSION=		0.6
PLUGIN_DEVEL=         YES
PLUGIN_COMMENT=		Control ubpbroadcastrelay processes
PLUGIN_DEPENDS=		udpbroadcastrelay
PLUGIN_MAINTAINER=	mjwasley@gmail.com

.include "../../Mk/plugins.mk"
