###################################################################
# Local syslog-ng configuration [cloudflared].
###################################################################
filter f_local_cloudflared {
    program("cloudflared");
};
