PLUGIN_NAME=        xymon-client
PLUGIN_VERSION=     1.0.0
PLUGIN_REVISION=    1
PLUGIN_DEPENDS=     xymon-client
PLUGIN_COMMENT=     Client for the Xymon network monitor
PLUGIN_MAINTAINER=  github+opnsense-xymon-client@kumy.net

.include "../../Mk/plugins.mk"
