#!/bin/sh
mkdir -p /var/db/rspamd
mkdir -p /var/log/rspamd
mkdir -p /var/run/rspamd

# fix permissions of files generated by configd
chmod +r /usr/local/etc/rspamd/local.d/*
chmod o+rx /usr/local/etc/rspamd/local.d
chown -R nobody /var/log/rspamd

chown nobody:nobody /var/db/rspamd
chown nobody:nobody /var/log/rspamd
chown nobody:nobody /var/run/rspamd
