PLUGIN_NAME=		shadowsocks
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		A secure socks5 proxy designed to protect your Internet traffic
PLUGIN_DEPENDS=		shadowsocks-libev
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
