PLUGIN_NAME=		lldpd
PLUGIN_VERSION=		1.1
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		LLDP allows you to know exactly on which port is a server
PLUGIN_DEPENDS=		lldpd
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
