PLUGIN_NAME=		lldpd
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		LLDP allows you to know exactly on which port is a server
PLUGIN_DEPENDS=		lldpd
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
