PLUGIN_NAME=		OPNProxy
PLUGIN_VERSION=		1.0.5
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		OPNsense proxy additions
PLUGIN_DEPENDS=		os-redis${PLUGIN_PKGSUFFIX} \
			os-squid${PLUGIN_PKGSUFFIX} \
			py${PLUGIN_PYTHON}-redis
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
