PLUGIN_NAME=		theme-vicuna
PLUGIN_VERSION=		1.45
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		The vicuna theme - blue sapphire
PLUGIN_MAINTAINER=	rene@team-rebellion.net
PLUGIN_NO_ABI=		yes

.include "../../Mk/plugins.mk"
