PLUGIN_NAME=		netdata
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Real-time performance monitoring
PLUGIN_DEPENDS=		netdata
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
