PLUGIN_NAME=		apuled
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Manage apuledctld daemon
PLUGIN_DEPENDS=		apuledctld
PLUGIN_MAINTAINER=	alexpro.ewr@gmail.com
PLUGIN_WWW=		https://smart-soft.ru

.include "../../Mk/plugins.mk"
