#!/bin/sh

board_id=$(smbmsg -f /dev/smb1 -s 0x62 -c 0x00 -i 1 | cut -c 4-5)

if [ ! -z $board_id ]; then
    # set front LED to green
    # format is -c (red) -o 2 (green) (blue) (some models lack a blue led)
    smbmsg -f /dev/smb1 -s 0x40 -c 0x00 -o 2 0xff 0x00
fi
