PLUGIN_NAME=		monit
PLUGIN_VERSION=		1.7
PLUGIN_VERSION=		1
PLUGIN_COMMENT=		Proactive system monitoring
PLUGIN_MAINTAINER=	frank.brendel@eurolog.com
PLUGIN_DEPENDS=		monit

.include "../../Mk/plugins.mk"
