#!/bin/sh

#
# Copyright (c) 2025 Arcan Consulting (www.arcan-it.de)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

# HCloudDNS CARP Transition Syshook
# Called by OPNsense on CARP state transitions
# Arguments: $1 = interface, $2 = MASTER|BACKUP|INIT

SUBSYSTEM="carp"
TYPE="${1}"
STATE="${2}"

logger -t hclouddns "CARP transition: interface=${TYPE} state=${STATE}"

case "${STATE}" in
    MASTER)
        # This node became MASTER - trigger DNS update
        # The Python script will verify CARP status again before updating
        logger -t hclouddns "CARP MASTER on ${TYPE} - triggering DNS update"
        /usr/local/sbin/configctl -d hclouddns update
        ;;
    BACKUP|INIT)
        logger -t hclouddns "CARP ${STATE} on ${TYPE} - no action"
        ;;
esac

exit 0
