[start]
command:service arp-ndp-logging start
parameters:
type:script
message:starting ARP/NDP Logging

[stop]
command:service arp-ndp-logging stop
parameters:
type:script
message:stopping ARP/NDP Logging

[restart]
command:service arp-ndp-logging restart
parameters:
type:script
message:restarting ARP/NDP Logging

[status]
command:service arp-ndp-logging status;exit 0
parameters:
type:script_output
message:request ARP/NDP Logging status

[resetdb]
command:rm -f /var/db/arp-ndp-logging/arp-ndp-logging.db; echo "`date '+%Y-%m-%d_%H:%M:%S,000'`: database reset" >> /var/log/arp-ndp-logging.log
parameters:
type:script
message:reset database
