###################################################################
# Local syslog-ng configuration filter definition [bind_dhcplease].
###################################################################
filter f_local_bind_dhcplease {
    program("bind-dhcplease");
};
