PLUGIN_NAME=		relayd
PLUGIN_VERSION=		2.7
#PLUGIN_REVISION=	1
PLUGIN_DEPENDS=		relayd
PLUGIN_COMMENT=		Relayd Load Balancer
PLUGIN_MAINTAINER=	frank.brendel@eurolog.com

.include "../../Mk/plugins.mk"
