PLUGIN_NAME=		relayd
PLUGIN_VERSION=		2.0.d
PLUGIN_DEPENDS=		relayd
PLUGIN_COMMENT=		Relayd Load Balancer
PLUGIN_MAINTAINER=		frank.brendel@eurolog.com
PLUGIN_REVISION=		1

.include "../../Mk/plugins.mk"
