PLUGIN_NAME=		theme-advanced
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		OPNsense theme based on AdvancedTomato GUI
PLUGIN_MAINTAINER=	jacky@prahec.com
PLUGIN_WWW=		https://prahec.com/
PLUGIN_NO_ABI=		yes

.include "../../Mk/plugins.mk"
