PLUGIN_NAME=		theme-advanced
PLUGIN_COMMENT=		OPNsense theme based on AdvancedTomato GUI
PLUGIN_VERSION=		1.1.0
PLUGIN_REVISION=	4
PLUGIN_COMMENT=		OPNSense Theme based on AdvancedTomato GUI
PLUGIN_MAINTAINER=	jacky@prahec.com
PLUGIN_WWW=			https://prahec.com/

.include "../../Mk/plugins.mk"
.include "../../Mk/plugins.mk"