PLUGIN_NAME=		lightscope
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		LightScope Cybersecurity Research Honeypot and Telescope
PLUGIN_MAINTAINER=	e@alumni.usc.edu
PLUGIN_WWW=		https://thelightscope.com
PLUGIN_DEPENDS=		python311

.include "../../Mk/plugins.mk"
