PLUGIN_NAME=		intrusion-detection-content-pt-open
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		IDS PT Research ruleset (only for non-commercial use)
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_WWW=		https://www.ptsecurity.com/ww-en/

.include "../../Mk/plugins.mk"
