PLUGIN_NAME=		intrusion-detection-content-ptopen
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		IDS Positive Technologies ESC ruleset
PLUGIN_MAINTAINER=	kulikov.a@gmail.com
PLUGIN_WWW=		https://rules.ptsecurity.com
.include "../../Mk/plugins.mk"
