PLUGIN_NAME=		intrusion-detection-content-pt-open
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		IDS PT Research ruleset (only for non-commercial use)
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
