PLUGIN_NAME=		dnscrypt-proxy
PLUGIN_VERSION=		2.0
PLUGIN_REVISION=	5
PLUGIN_COMMENT=		dnscrypt-proxy configuration front-end
PLUGIN_DEPENDS=		dnscrypt-proxy2
PLUGIN_MAINTAINER=	7823088+agh1467@users.noreply.github.com

.include "../../Mk/plugins.mk"
