PLUGIN_NAME=		icapeg
PLUGIN_VERSION=		1.0.0
PLUGIN_REVISION=	1
PLUGIN_DEPENDS=		icapeg
PLUGIN_COMMENT=		ICAP server implementation with Multi vendor support.
PLUGIN_MAINTAINER=	support@egirna.com

.include "../../Mk/plugins.mk"
