[server.list]
command:/usr/local/opnsense/scripts/iperf/server.py list
parameters:
type:script_output
message:list iperf server jobs

[server.create]
command:/usr/local/opnsense/scripts/iperf/server.py
parameters: --settings %s create
type:script_output
message:create iperf server job

[server.start]
command:/usr/local/opnsense/scripts/iperf/server.py
parameters: --job %s start
type:script_output
message:start iperf server job %s

[server.stop]
command:/usr/local/opnsense/scripts/iperf/server.py
parameters: --job %s stop
type:script_output
message:stop iperf server job %s

[server.remove]
command:/usr/local/opnsense/scripts/iperf/server.py
parameters: --job %s remove
type:script_output
message:remove iperf server job %s

[client.list]
command:/usr/local/opnsense/scripts/iperf/client.py list
parameters:
type:script_output
message:list iperf client jobs

[client.create]
command:/usr/local/opnsense/scripts/iperf/client.py
parameters: --settings %s create
type:script_output
message:create iperf client job

[client.start]
command:/usr/local/opnsense/scripts/iperf/client.py
parameters: --job %s start
type:script_output
message:start iperf client job %s

[client.stop]
command:/usr/local/opnsense/scripts/iperf/client.py
parameters: --job %s stop
type:script_output
message:stop iperf client job %s

[client.remove]
command:/usr/local/opnsense/scripts/iperf/client.py
parameters: --job %s remove
type:script_output
message:remove iperf client job %s
