[server.list]
command:/usr/local/opnsense/scripts/iperf/server.py list
parameters:
type:script_output
message:list iperf server jobs

[server.start]
command:/usr/local/opnsense/scripts/iperf/server.py
parameters: --port %s start
type:script_output
message:start iperf server on port %s

[server.remove]
command:/usr/local/opnsense/scripts/iperf/server.py
parameters: --job %s remove
type:script_output
message:remove iperf server job %s

[client.list]
command:/usr/local/opnsense/scripts/iperf/client.py list
parameters:
type:script_output
message:list iperf client jobs

[client.start]
command:/usr/local/opnsense/scripts/iperf/client.py
parameters: --job %s start
type:script_output
message:start iperf client job %s

[client.remove]
command:/usr/local/opnsense/scripts/iperf/client.py
parameters: --job %s remove
type:script_output
message:remove iperf client job %s
