PLUGIN_NAME=		telegram-notify
PLUGIN_VERSION=		1.0.2
PLUGIN_COMMENT=		Telegram notification manager
PLUGIN_MAINTAINER=	kuiper@local
PLUGIN_WWW=		https://core.telegram.org/bots/api

.include "../../Mk/plugins.mk"
