PLUGIN_NAME=		theme-dark-blueorange
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		OPNsense theme inspired by AdGuard Home
PLUGIN_MAINTAINER=	iengels@web.de
PLUGIN_WWW=		-
PLUGIN_NO_ABI=		yes

.include "../../Mk/plugins.mk"
