PLUGIN_NAME=		mail-backup
PLUGIN_VERSION=		1.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Send configuration file backup by e-mail
PLUGIN_DEPENDS=		gnupg phpmailer
PLUGIN_MAINTAINER=	machadovilaca@gmail.com

.include "../../Mk/plugins.mk"
