PLUGIN_NAME=		mail-backup
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Send configuration file backup by e-mail
PLUGIN_DEPENDS=		gnupg phpmailer
PLUGIN_MAINTAINER=	machadovilaca@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
