PLUGIN_NAME=		ddclient
PLUGIN_VERSION=		1.15
PLUGIN_DEPENDS=		ddclient-devel py${PLUGIN_PYTHON}-boto3
PLUGIN_COMMENT=		Dynamic DNS client
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
