PLUGIN_NAME=		ddclient
PLUGIN_VERSION=		1.23
PLUGIN_REVISION=	1
PLUGIN_DEPENDS=		ddclient py${PLUGIN_PYTHON}-boto3
PLUGIN_COMMENT=		Dynamic DNS client
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
