[start]
command:/usr/local/etc/rc.d/netflector start
type:script
message:starting netflector

[stop]
command:/usr/local/etc/rc.d/netflector stop
type:script
message:stopping netflector

[restart]
command:/usr/local/etc/rc.d/netflector restart
type:script
message:restarting netflector

[status]
command:/usr/local/etc/rc.d/netflector status
errors:no
type:script_output
message:netflector status

[report]
command:/usr/local/etc/rc.d/netflector report
type:script
message:dumping netflector diagnostics to the log
