PLUGIN_NAME=		net-snmp
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Net-SNMP is a daemon for the SNMP protocol
PLUGIN_DEPENDS=		net-snmp
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=       yes
.include "../../Mk/plugins.mk"
