PLUGIN_NAME=		net-snmp
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=        1
PLUGIN_COMMENT=		Net-SNMP is a daemon for the SNMP protocol
PLUGIN_DEPENDS=		net-snmp
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
