PLUGIN_NAME=		node_exporter
PLUGIN_VERSION=		0.1.0
PLUGIN_COMMENT=		Prometheus exporter for machine metrics
PLUGIN_DEPENDS=		node_exporter
PLUGIN_MAINTAINER=	dharrigan@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
