PLUGIN_NAME=		node_exporter
PLUGIN_VERSION=		1.2
PLUGIN_COMMENT=		Prometheus exporter for machine metrics
PLUGIN_DEPENDS=		node_exporter
PLUGIN_MAINTAINER=	jkegh@k123.eu

.include "../../Mk/plugins.mk"
