PLUGIN_NAME=		node_exporter
PLUGIN_VERSION=		1.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Prometheus exporter for machine metrics
PLUGIN_DEPENDS=		node_exporter
PLUGIN_MAINTAINER=	dharrigan@gmail.com

.include "../../Mk/plugins.mk"
