#!/bin/sh
#
# $FreeBSD$
#
# PROVIDE: opnsense-openconnect
# REQUIRE: SERVERS
# KEYWORD: shutdown
#

. /etc/rc.subr

name=openconnect

stop_cmd=openconnect_stop
start_cmd=openconnect_start
status_cmd=openconnect_status
rcvar=openconnect_enable

load_rc_config opnsense-openconnect
pidfile=/var/run/${name}.pid
command=/usr/local/sbin/${name}

[ -z "$openconnect_enable" ] && openconnect_enable="NO"

# status of openconnect
openconnect_status()
{
	 if [ -n "$rc_pid" ]; then
	     echo "${name} is running as pid $rc_pid."
	     return 0
	 else
	     echo "${name} is not running."
	 fi
}

# stop openconnect
openconnect_stop()
{
	echo "stopping openconnect"
	killall openconnect
	ifconfig ocvpn0 destroy
	return 0
}

# start openconnect
openconnect_start()
{
{% if helpers.exists('OPNsense.openconnect.general.enabled') and OPNsense.openconnect.general.enabled == '1' %}
{%   if helpers.exists('OPNsense.openconnect.general.server') and OPNsense.openconnect.general.server != '' %}
{%     if helpers.exists('OPNsense.openconnect.general.user') and OPNsense.openconnect.general.user != '' %}
{%       if helpers.exists('OPNsense.openconnect.general.password') and OPNsense.openconnect.general.password != '' %}  
        echo "starting openconnect"  
	echo "{{ OPNsense.openconnect.general.password }}" | /usr/local/sbin/openconnect -u {{ OPNsense.openconnect.general.user }} {{ OPNsense.openconnect.general.server }} --pid-file=/var/run/openconnect.pid -b -q -i tun30000 2>&1 > /dev/null
{%       endif %}
{%     endif %}
{%   endif %}
{% endif %}
        sleep 5
	ifconfig tun30000 name ocvpn0
	return 0
}

run_rc_command $1
