PLUGIN_NAME=		avahi-reflector
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Avahi mDNS/DNS-SD reflector for cross-VLAN service discovery
PLUGIN_MAINTAINER=	bflood@users.noreply.github.com
PLUGIN_DEPENDS=		avahi-app

.include "../../Mk/plugins.mk"
