PLUGIN_NAME=		avahi-reflector
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Avahi mDNS/DNS-SD reflector for cross-VLAN service discovery
PLUGIN_MAINTAINER=	23534755+cayossarian@users.noreply.github.com
PLUGIN_DEPENDS=		avahi-app
PLUGIN_CONFLICTS=	mdns-repeater

.include "../../Mk/plugins.mk"
