PLUGIN_NAME=		topology-map
PLUGIN_VERSION=		1.0_1
PLUGIN_COMMENT=		Network topology mapper with LLDP/ARP/NDP discovery
PLUGIN_MAINTAINER=	kuiper@local
PLUGIN_WWW=		https://opnsense.org

.include "../../Mk/plugins.mk"
