PLUGIN_NAME=		freeradius
PLUGIN_VERSION=		1.9.20
PLUGIN_COMMENT=		RADIUS Authentication, Authorization and Accounting Server
PLUGIN_DEPENDS=		freeradius3
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
