PLUGIN_NAME=            freeradius
PLUGIN_VERSION=         0.3.0
PLUGIN_COMMENT=         RADIUS Authentication, Authorization and Accounting Server
PLUGIN_DEPENDS=         freeradius3
PLUGIN_MAINTAINER=      m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
