PLUGIN_NAME=		email-config-backup
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Send global configuration file backup by email
PLUGIN_DEPENDS=		gnupg1 phpmailer
PLUGIN_MAINTAINER=	machadovilaca@gmail.com

.include "../../Mk/plugins.mk"
