PLUGIN_NAME=		etpro_telemetry
PLUGIN_VERSION=		1.0
#PLUGIN_REVISION=	1
PLUGIN_COMMENT=		ETPRO telemetry edition
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_WWW=		https://docs.opnsense.org/manual/etpro_telemetry.html

.include "../../Mk/plugins.mk"
