PLUGIN_NAME=		flowtriq
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		DDoS detection via NetFlow export to Flowtriq
PLUGIN_DEPENDS=		softflowd
PLUGIN_MAINTAINER=	jacob@traztech.ca

.include "../../Mk/plugins.mk"
