PLUGIN_NAME=		theme-advancedopn
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		OPNSense Theme based on AdvancedTomato GUI
PLUGIN_MAINTAINER=	jacky@prahec.com
PLUGIN_WWW=			https://prahec.com/

.include "../../Mk/plugins.mk"