PLUGIN_NAME=		cache
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Webserver cache
.if "${PLUGIN_PHP}" == "84"
PLUGIN_DEPENDS=		php${PLUGIN_PHP}-opcache
.endif
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
