PLUGIN_NAME=		wazuh-agent
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		Agent for the open source security platform Wazuh
PLUGIN_DEPENDS=		wazuh-agent
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
