PLUGIN_NAME=		wazuh-agent
PLUGIN_VERSION=		1.0.0
#PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Agent for the opensource security platform Wazuh
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_TIER=		3

.include "../../Mk/plugins.mk"
