PLUGIN_NAME=		virtualbox
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		VirtualBox additions
PLUGIN_DEPENDS=		virtualbox-ose-additions-nox11
PLUGIN_MAINTAINER=	project@opnsense.org

.include "../../Mk/plugins.mk"
