PLUGIN_NAME=		virtualbox
PLUGIN_VERSION=		0.1
PLUGIN_DEVEL=		yes
PLUGIN_COMMENT=		VirtualBox additions
PLUGIN_DEPENDS=		virtualbox-ose-additions-nox11
PLUGIN_MAINTAINER=	project@opnsense.org

.include "../../Mk/plugins.mk"
