#!/usr/local/bin/php
<?php

/*
 * Copyright (C) 2026 Sergii Bogomolov
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

require_once('config.inc');
require_once('interfaces.inc');
require_once('util.inc');

use OPNsense\Netflector\Netflector;
use OPNsense\Interfaces\Vip;

$subsystem = $argv[1] ?? '';
$type = $argv[2] ?? '';

if (!in_array($type, ['MASTER', 'BACKUP', 'INIT'], true) || strpos($subsystem, '@') === false) {
    exit(0);
}

$model = new Netflector();
if (!$model->general->enabled->isEqual('1') || !$model->general->carp_depend_on->isSet()) {
    exit(0);
}
$depends_on = $model->general->carp_depend_on->getValue();

$group = null;
foreach ((new Vip())->vip->iterateItems() as $uuid => $vip) {
    if ($uuid === $depends_on && $vip->mode->isEqual('carp')) {
        $group = sprintf('%s@%s', $vip->vhid->getValue(), get_real_interface($vip->interface->getValue()));
        break;
    }
}

if ($group === null) {
    log_msg('carp_depend_on names no CARP virtual IP; stopping netflector', LOG_ERR);
    mwexecf('/usr/local/etc/rc.d/netflector %s', ['stop'], true);
    exit(0);
}

if ($group !== $subsystem) {
    exit(0);
}

$action = $type === 'MASTER' ? 'start' : 'stop';
log_msg(sprintf('CARP %s is %s, running netflector %s', $subsystem, $type, $action));

mwexecf('/usr/local/etc/rc.d/netflector %s', [$action], $action === 'stop');
