PLUGIN_NAME=		api-backup
PLUGIN_VERSION=		1.1
PLUGIN_OBSOLETE=	yes
PLUGIN_COMMENT=		EoL, core endpoint is /api/core/backup/download/this
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
