PLUGIN_NAME=		snmp
PLUGIN_VERSION=		1.3
PLUGIN_DEPENDS=		bsnmp-regex bsnmp-ucd
PLUGIN_COMMENT=		End of life, superseded by Net-SNMP plugin
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
