PLUGIN_NAME=		snmp
PLUGIN_VERSION=		0.1
PLUGIN_PRIVATE=		yes
PLUGIN_DEPENDS=		bsnmp-regex bsnmp-ucd
PLUGIN_COMMENT=		SNMP Server via bsnmpd
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
