PLUGIN_NAME=		   zpool-scrub
PLUGIN_VERSION=		 1.0
PLUGIN_REVISION=	 1
PLUGIN_COMMENT=    Begins a ZFS pool scrub. The scrub examines all data in the specified pool to verify that it checksums correctly.
PLUGIN_DEPENDS=
PLUGIN_MAINTAINER= iain.henderson@mac.com

.include "../../Mk/plugins.mk"
