PLUGIN_NAME=		maltrail
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=        1
PLUGIN_COMMENT=		Malicious traffic detection system
PLUGIN_DEPENDS=		maltrail py27-sqlite3
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
