PLUGIN_NAME=		maltrail
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Malicious traffic detection system
PLUGIN_DEPENDS=		maltrail
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
