###################################################################
# Local syslog-ng configuration filter definition [avahi].
###################################################################
filter f_local_avahi {
    program("avahi-daemon");
};
