###################################################################
# Local syslog-ng configuration filter definition [netflector].
###################################################################
filter f_local_netflector {
    program("netflector");
};
