PLUGIN_NAME=		haproxy
PLUGIN_VERSION=		3.11
PLUGIN_COMMENT=		Reliable, high performance TCP/HTTP load balancer
PLUGIN_DEPENDS=		haproxy24
PLUGIN_MAINTAINER=	opnsense@moov.de

.include "../../Mk/plugins.mk"
