PLUGIN_NAME=		haproxy
PLUGIN_VERSION=		3.7
PLUGIN_COMMENT=		Reliable, high performance TCP/HTTP load balancer
PLUGIN_DEPENDS=		haproxy22
PLUGIN_MAINTAINER=	opnsense@moov.de

.include "../../Mk/plugins.mk"
