PLUGIN_NAME=		haproxy
PLUGIN_VERSION=		5.1
PLUGIN_COMMENT=		Reliable, high performance TCP/HTTP load balancer
PLUGIN_DEPENDS=		haproxy py${PLUGIN_PYTHON}-haproxy-cli
PLUGIN_MAINTAINER=	opnsense@moov.de

.include "../../Mk/plugins.mk"
