PLUGIN_NAME=		vnstat
PLUGIN_VERSION=		1.3
PLUGIN_COMMENT=		vnStat is a console-based network traffic monitor
PLUGIN_DEPENDS=		vnstat
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
