PLUGIN_NAME=		vnstat
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		vnStat is a console-based network traffic monitor
PLUGIN_DEPENDS=		vnstat
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=       yes

.include "../../Mk/plugins.mk"
