PLUGIN_NAME=		xcaddy
PLUGIN_VERSION=		0.1
PLUGIN_DEVEL=		yes
PLUGIN_DEPENDS=		xcaddy os-caddy
PLUGIN_COMMENT=		Build caddy with custom modules
PLUGIN_MAINTAINER=	cedrik@pischem.com

.include "../../Mk/plugins.mk"
