PLUGIN_NAME=            freeradius3
PLUGIN_VERSION=         0.0.1
PLUGIN_COMMENT=         Freeradius3
PLUGIN_DEPENDS=         talloc python2 gdbm
PLUGIN_MAINTAINER=      m.muenz@gmail.com

.include "../../Mk/plugins.mk"
