PLUGIN_NAME=		fetchmail
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Remote-mail retrieval utility
PLUGIN_DEPENDS=		fetchmail
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=       yes

.include "../../Mk/plugins.mk"
