PLUGIN_NAME=		etpro-telemetry
PLUGIN_VERSION=		1.3
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		ET Pro Telemetry Edition
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_WWW=		https://docs.opnsense.org/manual/etpro_telemetry.html

.include "../../Mk/plugins.mk"
