PLUGIN_NAME=		etpro-telemetry
PLUGIN_VERSION=		1.7
PLUGIN_REVISION=	5
PLUGIN_COMMENT=		ET Pro Telemetry Edition
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_DEPENDS=		py${PLUGIN_PYTHON}-netaddr
PLUGIN_WWW=		https://docs.opnsense.org/manual/etpro_telemetry.html
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
