#!/usr/local/bin/php
<?php

/*
 * Copyright (C) 2026 Brendan Bank
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * Metrics exporter daemon.
 * Reads exporter configuration from /usr/local/etc/metrics_exporter.conf
 * (generated by generate_config.php via configd).
 * Discovers and runs enabled collectors to produce Prometheus metrics.
 */

require_once __DIR__ . '/lib/collector_loader.php';

define('CONFIG_PATH', '/usr/local/etc/metrics_exporter.conf');
define('COLLECTORS_DIR', __DIR__ . '/collectors');

openlog('metrics_exporter', LOG_DAEMON, LOG_LOCAL4);

$reconfigure = true;
$running = true;

pcntl_signal(SIGHUP, function () use (&$reconfigure) {
    $reconfigure = true;
});

pcntl_signal(SIGTERM, function () use (&$running) {
    $running = false;
});

pcntl_signal(SIGINT, function () use (&$running) {
    $running = false;
});

$interval = 15;
$output_dir = '/var/tmp/node_exporter/';
$enabled_collectors = [];
$written_files = [];

syslog(LOG_NOTICE, sprintf('Metrics exporter starting (pid=%d)', getmypid()));

while ($running) {
    pcntl_signal_dispatch();

    if (!$running) {
        break;
    }

    if ($reconfigure) {
        $json = @file_get_contents(CONFIG_PATH);
        if ($json === false) {
            syslog(LOG_ERR, 'Metrics exporter: cannot read config file, using defaults');
        } else {
            $config = json_decode($json, true);
            if ($config === null) {
                syslog(LOG_ERR, 'Metrics exporter: invalid config JSON, using defaults');
            } else {
                $interval = $config['interval'] ?? 15;
                if ($interval < 5 || $interval > 300) {
                    $interval = 15;
                }

                $output_dir = $config['outputdir'] ?? '/var/tmp/node_exporter/';
                if (empty($output_dir) || strpos($output_dir, '..') !== false) {
                    $output_dir = '/var/tmp/node_exporter/';
                }
                if (substr($output_dir, -1) !== '/') {
                    $output_dir .= '/';
                }

                $all_collectors = load_collectors(COLLECTORS_DIR);
                $config_collectors = $config['collectors'] ?? [];

                // Remove .prom files for collectors that are no longer enabled
                $old_types = array_keys($enabled_collectors);
                $enabled_collectors = [];
                foreach ($all_collectors as $type => $class) {
                    if (isset($config_collectors[$type]) && $config_collectors[$type]) {
                        $enabled_collectors[$type] = $class;
                    }
                }

                // Clean up files for collectors that were disabled
                foreach ($old_types as $old_type) {
                    if (!isset($enabled_collectors[$old_type])) {
                        $old_file = $output_dir . $old_type . '.prom';
                        @unlink($old_file);
                        unset($written_files[$old_type]);
                    }
                }
            }
        }

        $collector_names = implode(', ', array_keys($enabled_collectors));
        syslog(LOG_NOTICE, sprintf(
            'Metrics exporter configured: interval=%ds, outputdir=%s, '
                . 'collectors(%d): %s',
            $interval,
            $output_dir,
            count($enabled_collectors),
            $collector_names ?: '(none)'
        ));

        $reconfigure = false;
    }

    foreach ($enabled_collectors as $type => $class) {
        try {
            $output = $class::collect();
        } catch (\Throwable $e) {
            syslog(LOG_WARNING, sprintf(
                'Metrics exporter: collector %s failed: %s',
                $type,
                $e->getMessage()
            ));
            continue;
        }

        $prom_path = $output_dir . $type . '.prom';
        $tmp_path = $prom_path . '.tmp.' . getmypid();
        if (@file_put_contents($tmp_path, $output) !== false) {
            @chmod($tmp_path, 0644);
            if (!@rename($tmp_path, $prom_path)) {
                syslog(
                    LOG_WARNING,
                    'Metrics exporter: failed to rename temp file for ' . $type
                );
                @unlink($tmp_path);
            } else {
                $written_files[$type] = $prom_path;
            }
        } else {
            syslog(
                LOG_WARNING,
                'Metrics exporter: failed to write temp file for ' . $type
            );
            @unlink($tmp_path);
        }
    }

    sleep($interval);
}

// Cleanup on exit
syslog(LOG_NOTICE, 'Metrics exporter stopping');
foreach ($written_files as $file) {
    @unlink($file);
}
closelog();
