PLUGIN_NAME=          rspamd
PLUGIN_VERSION=       0.1
PLUGIN_COMMENT=       Protect your network from spam
PLUGIN_DEPENDS=       rspamd
PLUGIN_MAINTAINER=    franz.fabian.94@gmail.com
PLUGIN_DEVEL=         YES

.include "../../Mk/plugins.mk"
