PLUGIN_NAME=		rspamd
PLUGIN_VERSION=		1.12
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Protect your network from spam
PLUGIN_DEPENDS=		rspamd
PLUGIN_MAINTAINER=	franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
