PLUGIN_NAME=		smart2
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		SMART tools
PLUGIN_DEPENDS=		smartmontools
#PLUGIN_MAINTAINER=	franco@opnsense.org
PLUGIN_MAINTAINER=	Kirpa.Sergey@gmail.com

.include "../../Mk/plugins.mk"
