PLUGIN_NAME=       unbound-diagnostics
PLUGIN_VERSION=    0.0.1
PLUGIN_COMMENT=    Brings the support of some debugging of unbound to OPNsense
PLUGIN_DEPENDS=    ruby unbound
PLUGIN_MAINTAINER= franz.fabian.94@gmail.com
PLUGIN_DEVEL =     yes

.include "../../Mk/plugins.mk"
