PLUGIN_NAME=		ndp-proxy-go
PLUGIN_VERSION=		1.2
PLUGIN_COMMENT=		IPv6 Neighbor Discovery Protocol (NDP) Proxy
PLUGIN_MAINTAINER=	cedrik@pischem.com
PLUGIN_DEPENDS=		ndp-proxy-go

.include "../../Mk/plugins.mk"
