PLUGIN_NAME=		ndp-proxy-go
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		IPv6 Neighbor Discovery Protocol Proxy
PLUGIN_MAINTAINER=	cedrik@pischem.com
PLUGIN_DEPENDS=		ndp-proxy-go

.include "../../Mk/plugins.mk"
