#!/bin/sh

#ichsmb has to load first, so that ismt is at /dev/smb1 (or adjust the script)
needed_klds="ichsmb ismt smb"

kldload $needed_klds &> /dev/null
sleep 1

ismt_dev=/dev/smb1

board_id=$(smbmsg -f $ismt_dev -s 0x62 -c 0x00 -i 1 | cut -c 4-5)

if [ ! -z $board_id ]; then

    # Disable PIC Watch Dog
    smbmsg -f $ismt_dev -s 0x44 -c 0 -o 1 0
    # Set PIC Watch Dog default count to 0 (offset 0x0=LSB; 0x1=MSB)
    smbmsg -f $ismt_dev -s 0x48 -c 0x0 -o 1 0x0
    sleep 1
    smbmsg -f $ismt_dev -s 0x48 -c 0x1 -o 1 0x0

    

    if [ x"$board_id" = x"8" ] || [ x"$board_id" = x"a" ] || [ x"$board_id" = x"b" ]; then
        logger -t "vep1400-hw" "VEP1400-X detected, doing init"
        # VEP1400-X stuff
        # fetch board type
        # smbmsg -f $ismt_dev -s 0x62 -c 0x00 -i 1 | cut -c 4-5
        # if 8, 10(a) or 11(b), do the following
        # i2cset -y 1 0x31 0x1 0xff

        #enable the i350 GbE ports
        smbmsg -f $ismt_dev -s 0x62 -c 0x01 -o 1 0xff

        # more VEP1400-x stuff
        # Communicate with CPLD/FPGA to turn off SFP TX disable (DAC cables aren't affected by this)
        # for ix1
        smbmsg -f $ismt_dev -s 0x62 -c 0x10 -o 1 0x07
        # for ix0
        smbmsg -f $ismt_dev -s 0x62 -c 0x11 -o 1 0x07
    fi

    if [ x"$board_id" = x"0" ]; then
        logger -t "vep1400-hw" "VEP1400 detected, doing init"
        #Communicate with CPLD/FPGA to turn off SFP TX disable (DAC cables aren't affected by this)
        # for ix3
        smbmsg -f $ismt_dev -s 0x62 -c 0x10 -o 1 0
        # for ix2
        smbmsg -f $ismt_dev -s 0x62 -c 0x11 -o 1 0
        if [ -e /dev/etherswitch0 ]; then
            etherswitchcfg config vlan_mode dot1q
            etherswitchcfg port1 pvid 2 port2 pvid 2 port3 pvid 2 port4 pvid 2 port5 pvid 2 port6 pvid 3 port9 pvid 3 port10 pvid 2 vlangroup0 vlan 2 members 1,2,3,4,5,10 vlangroup1 vlan 3 members 6,9
            echo "Marvell 88E6190 configured. LAN ports are 1-5 and are connected to ix0. WAN is on port 6 and is connected to ix1."
            logger -t "vep1400-hw" "Marvell 88E6190 configured. LAN is on ports 1-5 and is connected to ix0. WAN is on port 6 and is connected to ix1."
        else
            logger -t "vep1400-hw" "VEP1400 detected, but no etherswitch dev found. Is patched kernel installed?"
        fi
    fi
fi

