PLUGIN_NAME=          nginx
PLUGIN_VERSION=       0.1
PLUGIN_COMMENT=       nginx proxy and webserver
PLUGIN_DEPENDS=       nginx
PLUGIN_MAINTAINER=    franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
