PLUGIN_NAME=          tor
PLUGIN_VERSION=       1.6
PLUGIN_COMMENT=       The Onion Router
PLUGIN_DEPENDS=       tor ruby
PLUGIN_MAINTAINER=    franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
