PLUGIN_NAME=          tor
PLUGIN_VERSION=       0.2
PLUGIN_COMMENT=       The Onion Router
PLUGIN_DEPENDS=       tor
PLUGIN_MAINTAINER=    franz.fabian.94@gmail.com
PLUGIN_DEVEL=         yes

.include "../../Mk/plugins.mk"
