PLUGIN_NAME=		gdrive-backup
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Backup configurations using Google Drive
PLUGIN_DEPENDS=		php${PLUGIN_PHP}-google-api-php-client
PLUGIN_MAINTAINER=	ad@opnsense.org

.include "../../Mk/plugins.mk"
