PLUGIN_NAME=		gdrive-backup
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Backup configurations using Google Drive
PLUGIN_DEPENDS=		php${PLUGIN_PHP}-google-api-php-client
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
