PLUGIN_NAME=		step-certificates
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		StepCA Certificate Authority for OPNSense
PLUGIN_DEPENDS=		security/step-certificates \
					security/step-kms \
					devel/pcsc-lite
					# security/py-yubikey-manager
PLUGIN_MAINTAINER=	step-opn@papro.ca

.include "../../Mk/plugins.mk"
