PLUGIN_NAME=		hw-probe
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Collect hardware diagnostics
PLUGIN_DEPENDS=		hw-probe
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=       yes

.include "../../Mk/plugins.mk"
