PLUGIN_NAME=		telegraf
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Agent for collecting metrics and data
PLUGIN_DEPENDS=		telegraf
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=           yes

.include "../../Mk/plugins.mk"
