PLUGIN_NAME=		telegraf
PLUGIN_VERSION=		1.12.12
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Agent for collecting metrics and data
PLUGIN_DEPENDS=		telegraf
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
