PLUGIN_NAME=		qemu-guest-agent
PLUGIN_VERSION=		1.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		QEMU Guest Agent for OPNsense
PLUGIN_DEPENDS=		qemu-guest-agent
PLUGIN_MAINTAINER=	opnsense@moov.de

.include "../../Mk/plugins.mk"
