PLUGIN_NAME=		autorollback
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Automatic configuration rollback with safe mode
PLUGIN_MAINTAINER=	github.immobile762@passmail.net
PLUGIN_WWW=		https://github.com/mplind/os-autorollback
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
