PLUGIN_NAME=		openvpn-legacy
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		OpenVPN legacy support
PLUGIN_DEPENDS=		# openvpn
PLUGIN_DEVEL=		yes
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
