#!/bin/sh
#    Copyright (C) 2019-2020 Cloudfence - JCC
#    All rights reserved.
#
#    Redistribution and use in source and binary forms, with or without
#    modification, are permitted provided that the following conditions are met:
#
#    1. Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.#
#
#    2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
#    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
#    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
#    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#    POSSIBILITY OF SUCH DAMAGE.

name=webfilter
rcvar=webfilter_enable

. /etc/rc.subr

# Vars
USERLIST_PATH="/usr/local/etc/squid/db"

case "$1" in
start)
    logger -t "WebFilter" "Starting service..."
    configctl proxy start
    ;;
stop)
    logger -t "WebFilter" "Stopping service..."
    configctl proxy stop
    ;;
restart)
    "$0" stop && "$0" start
    /usr/local/opnsense/scripts/webfilter/webfilter-reload.sh reconfigure
    configctl template reload OPNsense/WebFilter
    ;;
*)
        echo "Usage: `basename $0` {start|stop|restart|force-join}" >&2
        exit 64
        ;;
esac

exit 0
