PLUGIN_NAME=		debug
PLUGIN_VERSION=		1.2
PLUGIN_COMMENT=		Debugging Tools
PLUGIN_DEPENDS=		php${PLUGIN_PHP}-pear-PHP_CodeSniffer \
			php${PLUGIN_PHP}-pecl-xdebug \
			phpunit6-php${PLUGIN_PHP}
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
