PLUGIN_NAME=		debug
PLUGIN_VERSION=		1.5
PLUGIN_COMMENT=		Debugging Tools
PLUGIN_DEPENDS=		php${PLUGIN_PHP}-pear-PHP_CodeSniffer \
			php${PLUGIN_PHP}-pecl-xdebug \
			phpunit9-php${PLUGIN_PHP} \
			py${PLUGIN_PYTHON}-pycodestyle \
			p5-File-Slurp git
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
