PLUGIN_NAME=		debug
PLUGIN_VERSION=		1.3
PLUGIN_COMMENT=		Debugging Tools
PLUGIN_DEPENDS=		php${PLUGIN_PHP}-pear-PHP_CodeSniffer \
			php${PLUGIN_PHP}-pecl-xdebug \
			phpunit6-php${PLUGIN_PHP} \
			p5-File-Slurp py27-pycodestyle \
			vim-console git
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
