[start]
command:service opnarplog start
parameters:
type:script
message:starting OPNarplog

[stop]
command:service opnarplog stop
parameters:
type:script
message:stopping OPNarplog

[restart]
command:service opnarplog restart
parameters:
type:script
message:restarting OPNarplog

[status]
command:service opnarplog status;exit 0
parameters:
type:script_output
message:request OPNarplog status

[resetdb]
command:rm -f /var/db/opnarplog/opnarplog.db; echo "`date '+%Y-%m-%d_%H:%M:%S,000'`: database reset" >> /var/log/opnarplog.log
parameters:
type:script
message:reset database
