# DO NOT EDIT
# THIS FILE IS AUTOMATICALLY GENERATED - ANY CHANGES WILL BE OVERWRITTEN
#
{% if not helpers.empty('OPNsense.tailscale.settings.enabled')  %}
tailscaled_enable="YES"
{%   if helpers.exists('OPNsense.tailscale.settings.listenPort') %}
tailscaled_port="{{ OPNsense.tailscale.settings.listenPort }}"
{%   endif %}
{%   if helpers.exists('OPNsense.tailscale.settings.advertiseExitNode') and OPNsense.tailscale.settings.advertiseExitNode|default("0") == "1" %}
tailscaled_exitnode_enable="YES"
{%   endif %}
{% set up_args = ["--reset"] %}
{%   if helpers.exists('OPNsense.tailscale.settings.acceptSubnetRoutes') and OPNsense.tailscale.settings.acceptSubnetRoutes|default("0") == "1" %}
{%     do up_args.append(" --accept-routes") %}
{%   endif %}
{%   if helpers.exists('OPNsense.tailscale.settings.acceptDNS') and OPNsense.tailscale.settings.acceptDNS|default("0") == "1" %}
{%     do up_args.append(" --accept-dns") %}
{%   endif %}
{%   if helpers.exists('OPNsense.tailscale.authentication.loginServer') %}
{%     do up_args.append(" --login-server=" + OPNsense.tailscale.authentication.loginServer) %}
{%   endif %}
{%   if helpers.exists('OPNsense.tailscale.authentication.preAuthKey') %}
{%     do up_args.append(" --auth-key=" + OPNsense.tailscale.authentication.preAuthKey) %}
{%   endif %}
{# loop through subnets to build list #}
{%   if helpers.exists('OPNsense.tailscale.settings.subnets.subnet4') %}
{%     set subnets = [] %}
{%     for subnet_list in helpers.toList('OPNsense.tailscale.settings.subnets.subnet4') %}
{%       do subnets.append(subnet_list.subnet) %}
{%     endfor %}
{%     set subnetString = subnets|join(',') %}
{%     do up_args.append(" --advertise-routes=" + subnetString) %}
{%   endif %}
tailscaled_up_args="{{ up_args|join(' ') }}"
{% else %}
tailscaled_enable=NO
{% endif %}

