# DO NOT EDIT
# THIS FILE IS AUTOMATICALLY GENERATED - ANY CHANGES WILL BE OVERWRITTEN
#
{% if helpers.exists('OPNsense.tailscale.settings.enabled') and OPNsense.tailscale.settings.enabled|default("0") == "1" %}
tailscaled_enable="YES"

{% if helpers.exists('OPNsense.tailscale.settings.listenPort') %}
tailscaled_port="{{ OPNsense.tailscale.settings.listenPort }}"
{% endif %}

{% if helpers.exists('OPNsense.tailscale.settings.advertiseExitNode') and OPNsense.tailscale.settings.advertiseExitNode|default("0") == "1" %}
tailscaled_exitnode_enable="YES"
{% endif %}

{% set up_args = "--reset" %}
{% if helpers.exists('OPNsense.tailscale.settings.acceptSubnetRoutes') and OPNsense.tailscale.settings.acceptSubnetRoutes|default("0") == "1" %}
{%   set up_args = up_args + " --accept-routes" %}
{% endif %}

{% if helpers.exists('OPNsense.tailscale.settings.acceptDNS') and OPNsense.tailscale.settings.acceptDNS|default("0") == "1" %}
{%   set up_args = up_args + " --accept-dns" %}
{% endif %}

{% if helpers.exists('OPNsense.tailscale.authentication.loginServer') %}
{%   set up_args = up_args + " --login-server=" + OPNsense.tailscale.authentication.loginServer %}
{% endif %}

{% if helpers.exists('OPNsense.tailscale.authentication.preAuthKey') %}
{%   set up_args = up_args + " --auth-key=" + OPNsense.tailscale.authentication.preAuthKey %}
{% endif %}

{# loop through subnets to build list #}
{% if helpers.exists('OPNsense.tailscale.settings.subnets.subnet4') %}
{%   set subnets = [] %}
{%   for subnet_list in helpers.toList('OPNsense.tailscale.settings.subnets.subnet4') %}
       {{ subnets.append(subnet_list.subnet) or "" }}
{%   endfor %}
{%   set subnetString = subnets|join(',') %}
{%   set up_args = up_args + " --advertise-routes=" + subnetString %}
{% endif %}

tailscaled_up_args="{{ up_args }}"

{% else %}
tailscaled_enable=NO
{% endif %}

