L# DO NOT EDIT
# THIS FILE IS AUTOMATICALLY GENERATED - ANY CHANGES WILL BE OVERWRITTEN
#
{%  if not helpers.empty('OPNsense.tailscale.settings.enabled')  %}
tailscaled_set_enable="YES"
{%    set set_args = [] %}
{%      do set_args.append("--relay-server-port=" + OPNsense.tailscale.settings.relayServerPort|default("")) %}
{%    if helpers.exists('OPNsense.tailscale.settings.webclient') and OPNsense.tailscale.settings.webclient|default("0") == "1" %}
{%      do set_args.append("--webclient") %}
{%    else %}
{%      do set_args.append("--webclient=false") %}
{%    endif %}
tailscaled_set_args="{{ set_args|join(' ') }}"
{%  else %}
tailscaled_set_enable="NO"
{%  endif %}

