[start]
command:/usr/local/etc/rc.d/cloudflared start
parameters:
type:script
message:Starting Cloudflare Tunnel

[stop]
command:/usr/local/etc/rc.d/cloudflared stop
parameters:
type:script
message:Stopping Cloudflare Tunnel

[restart]
command:/usr/local/etc/rc.d/cloudflared restart
parameters:
type:script
message:Restarting Cloudflare Tunnel

[status]
command:/usr/local/etc/rc.d/cloudflared status;exit 0
parameters:
type:script_output
message:Probing Cloudflare Tunnel

[reconfigure]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/Cloudflared/reconfigure.sh
parameters:
type:script
message:Reconfiguring Cloudflare Tunnel

[install_binary]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/Cloudflared/install_binary.sh;exit 0
parameters:
type:script_output
message:Installing Cloudflare Tunnel binary

[tunnel_status]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/Cloudflared/tunnel_status.sh;exit 0
parameters:
type:script_output
message:Checking Cloudflare Tunnel status
