[start]
command:service cloudflared start
parameters:
type:script
message:Starting Cloudflare Tunnel service

[stop]
command:service cloudflared stop
parameters:
type:script
message:Stopping Cloudflare Tunnel service

[restart]
command:service cloudflared restart
parameters:
type:script
message:Restarting Cloudflare Tunnel service
description:Restart Cloudflare Tunnel

[status]
command:service cloudflared status; exit 0
parameters:
type:script_output
message:Requesting Cloudflare Tunnel status

[recover]
command:/usr/local/opnsense/scripts/OPNsense/Cloudflared/recover.sh
parameters:
type:script
message:Recovering Cloudflare Tunnel
description:Recover Cloudflare Tunnel (start if not running)

[reconfigure]
command:/usr/local/opnsense/scripts/OPNsense/Cloudflared/reconfigure.sh
parameters:
type:script
message:Reconfiguring Cloudflare Tunnel
