PLUGIN_NAME=		turnserver
PLUGIN_VERSION=		0.1
PLUGIN_DEVEL=		yes
PLUGIN_COMMENT=		The coturn STUN/TURN Server
PLUGIN_DEPENDS=		turnserver
PLUGIN_MAINTAINER=	opnsense@moov.de

.include "../../Mk/plugins.mk"
