PLUGIN_NAME=		pppoe-server
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		PPPoE Access Concentrator (BRAS) based on mpd5
PLUGIN_DEPENDS=		mpd5
PLUGIN_MAINTAINER=	dev@veqnora.com
PLUGIN_WWW=		https://veqnora.com
PLUGIN_LICENSE=		BSD2CLAUSE

.include "../../Mk/plugins.mk"
