PLUGIN_NAME=		strongswan-legacy
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		IPsec legacy support
PLUGIN_DEPENDS=		# strongswan
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
