PLUGIN_NAME=       routing
PLUGIN_VERSION=    0.0.1
PLUGIN_COMMENT=    Plugin to manage quagga routing daemon software
PLUGIN_MAINTAINER= franz.fabian.94@gmail.com
PLUGIN_DEVEL =     devel

.include "../../Mk/plugins.mk"
