PLUGIN_NAME=		wireguard
PLUGIN_VERSION=		1.13
PLUGIN_REVISION=	7
PLUGIN_COMMENT=		WireGuard VPN service kernel implementation
PLUGIN_DEPENDS=		wireguard-kmod wireguard-tools
PLUGIN_CONFLICTS=	wireguard-go
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
