PLUGIN_NAME=		wireguard
PLUGIN_VERSION=		2.0
PLUGIN_COMMENT=		WireGuard VPN service
PLUGIN_DEPENDS=		wireguard-kmod
PLUGIN_MAINTAINER=	ad@opnsense.org

PLUGIN_CONFLICTS=	wireguard-go

.include "../../Mk/plugins.mk"
