PLUGIN_NAME=		wireguard
PLUGIN_VERSION=		0.11
PLUGIN_COMMENT=		WireGuard VPN service
PLUGIN_DEPENDS=		wireguard
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
