PLUGIN_NAME=		puppet-agent
PLUGIN_VERSION=		0.1
PLUGIN_DEVEL=		yes
PLUGIN_COMMENT=		Manage Puppet Agent
PLUGIN_DEPENDS=		puppet7
PLUGIN_MAINTAINER=	jan.wink93@gmail.com

.include "../../Mk/plugins.mk"
