PLUGIN_NAME=		puppet-agent
PLUGIN_VERSION=		0.2
PLUGIN_DEVEL=		yes
PLUGIN_COMMENT=		Manage Puppet Agent
PLUGIN_DEPENDS=		puppet7 py${PLUGIN_PYTHON}-opn-cli
PLUGIN_MAINTAINER=	jan.wink93@gmail.com

.include "../../Mk/plugins.mk"
