PLUGIN_NAME=		intrusion-detection-content-et-open
PLUGIN_VERSION=		1.0.0
#PLUGIN_REVISION=	1
PLUGIN_COMMENT=		IDS Proofpoint ET open ruleset, duplicates some rule files which are being delivered empty in ET Pro Telemetry edition so both can be installed
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_WWW=		https://rules.emergingthreats.net/

.include "../../Mk/plugins.mk"
