PLUGIN_NAME=		intrusion-detection-content-et-open
PLUGIN_VERSION=		1.0.2
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		IDS Proofpoint full ET open ruleset complementary subset for ET Pro Telemetry edition
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_WWW=		https://rules.emergingthreats.net/

.include "../../Mk/plugins.mk"
