PLUGIN_NAME=		salt-minion
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Manage Salt Minion
PLUGIN_DEPENDS=		py${PLUGIN_PYTHON}-salt py${PLUGIN_PYTHON}-opn-cli
PLUGIN_MAINTAINER=	git@monkz.de

.include "../../Mk/plugins.mk"
