[start]
command:/usr/local/bin/php /usr/local/opnsense/scripts/xproxy/sync_gateway.php;/usr/local/opnsense/scripts/xproxy/service_control.py start
parameters:
type:script
message:starting xproxy

[stop]
command:/usr/local/opnsense/scripts/xproxy/service_control.py stop
parameters:
type:script
message:stopping xproxy

[restart]
command:/usr/local/bin/php /usr/local/opnsense/scripts/xproxy/sync_gateway.php;/usr/local/opnsense/scripts/xproxy/service_control.py restart
parameters:
type:script
message:restarting xproxy
description:Restart Xproxy

[reconfigure]
command:/usr/local/bin/php /usr/local/opnsense/scripts/xproxy/sync_gateway.php;/usr/local/opnsense/scripts/xproxy/service_control.py reconfigure
parameters:
type:script
message:reconfiguring xproxy

[reload]
command:/usr/local/bin/php /usr/local/opnsense/scripts/xproxy/sync_gateway.php;/usr/local/opnsense/scripts/xproxy/service_control.py reconfigure
parameters:
type:script
message:reloading xproxy

[status]
command:/usr/local/opnsense/scripts/xproxy/service_control.py status
parameters:
type:script_output
message:request xproxy status

[log]
command:/usr/local/opnsense/scripts/xproxy/show_log.py
parameters:
type:script_output
message:request xproxy log

[import]
command:/usr/local/opnsense/scripts/xproxy/import_uris.py
parameters:%s
type:script_output
message:importing proxy URIs

[setup]
command:/usr/local/opnsense/scripts/xproxy/setup.sh
parameters:
type:script
message:setting up xproxy dependencies
