PLUGIN_NAME=        interfaces_plus_widget
PLUGIN_VERSION=	    0.1
PLUGIN_REVISION=    1
PLUGIN_COMMENT=     Added features over the default interfaces widget
PLUGIN_MAINTAINER=  mjwasley@gmail.com
PLUGIN_DEVEL=       no

.include "../../Mk/plugins.mk"
