[getfan]
command:/usr/local/opnsense/scripts/vephw/vep1400_get_fan_speed.sh
parameters:
type:script_output
message:Get VEP Fan speed

[setfan]
command:/usr/local/opnsense/scripts/vephw/vep1400_set_fan_speed.sh
parameters:%s %s
type:script
message:Set VEP Fan speed

[gettemp]
command:/usr/local/opnsense/scripts/vephw/vep1400_get_temp.sh
parameters:
type:script_output
message:Get VEP board temp

[getid]
command:/usr/local/opnsense/scripts/vephw/vep1400_get_id.sh
parameters:
type:script_output
message:Get VEP board id


[setled]
command:/usr/local/opnsense/scripts/vephw/vep1400_set_led.sh
parameters:%s %s %s
type:script
message:Set VEP front LED color