[getfan]
command:/usr/local/opnsense/scripts/vephw/vep1400_get_fan_speed.sh
parameters:
type:script_output
message:Get VEP Fan speed

[setfan]
command:/usr/local/opnsense/scripts/vephw/vep1400_set_fan_speed.sh
parameters:%s
type:script
message:Set VEP Fan speed

[gettemp]
command:/usr/local/opnsense/scripts/vephw/vep1400_get_temp.sh
parameters:
type:script_output
message:Get VEP board temp
