PLUGIN_NAME=		beats8
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	0
PLUGIN_COMMENT=		Send logs, network, metrics and heartbeat to elasticsearch
PLUGIN_DEPENDS=		beats8
PLUGIN_MAINTAINER=	0xThiebaut

.include "../../Mk/plugins.mk"
