PLUGIN_NAME=		cloudflared
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Cloudflare Tunnel integration
PLUGIN_MAINTAINER=	rick+github@insanityinside.net
PLUGIN_DEPENDS=		cloudflared

.include "../../Mk/plugins.mk"
