PLUGIN_NAME=	SSOActiveDirectory
PLUGIN_VERSION= 0.1
PLUGIN_COMMENT=	Add SSO Active Directory to use in Proxy
#PLUGIN_DEPENDS= sysutils/msktutil \
	security/cyrus-sasl2-gssapi \
	security\cyrus-sasl2 \
	net/openldap24-sasl-client
PLUGIN_MAINTAINER= gitdevmod@github.com

.include "../../Mk/plugins.mk"
