PLUGIN_NAME=		isc-dhcp
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		ISC DHCPv4/v6 server
PLUGIN_DEPENDS=		isc-dhcp44-server
PLUGIN_MAINTAINER=	franco@opnsense.org
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
