PLUGIN_NAME=		chrony
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Chrony time synchronisation
PLUGIN_DEPENDS=		chrony
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=       yes

.include "../../Mk/plugins.mk"
