PLUGIN_NAME=       ARP Scan
PLUGIN_VERSION=    0.1
PLUGIN_COMMENT=    Get all peers connected to a LAN using arp-scan
PLUGIN_MAINTAINER= giuseppe.demarco@unical.it
PLUGIN_DEPENDS=    arp-scan

.include "../../Mk/plugins.mk"
