PLUGIN_NAME=       ARP Scan
PLUGIN_VERSION=    0.1
PLUGIN_COMMENT=    Get all peers connected to a LAN
PLUGIN_MAINTAINER= giuseppe.demarco@unical.it
PLUGIN_DEPENDS=    arp-scan
PLUGINS_DEVEL= yes

.include "../../Mk/plugins.mk"
