PLUGIN_NAME=		bind
PLUGIN_VERSION=		1.4
PLUGIN_REVISION=        1
PLUGIN_COMMENT=		BIND domain name service
PLUGIN_DEPENDS=		bind912
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
