PLUGIN_NAME=		dnscrypt-proxy
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Flexible DNS proxy supportung DNSCrypt and DoH
PLUGIN_DEPENDS=		dnscrypt-proxy2
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
