PLUGIN_NAME=		dnscrypt-proxy
PLUGIN_VERSION=		1.12
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Flexible DNS proxy supporting DNSCrypt and DoH
PLUGIN_DEPENDS=		dnscrypt-proxy2
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
