PLUGIN_NAME=		theme-rebellion
PLUGIN_VERSION=		0.2
PLUGIN_REVISION=	3
PLUGIN_COMMENT=		A suitably dark theme
PLUGIN_MAINTAINER=	team-rebellion@queens-park.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
