#!/bin/sh
# REQUIRE: LOGIN DAEMON
. /etc/rc.subr
name=iperf
rcvar=iperf_enable
command_interpreter=/usr/local/bin/ruby
command=/usr/local/opnsense/scripts/iperf/ruby_iperf.rb
iperf_user=root
iperf_pidfile=/var/run/iperf.pid
start_cmd="/usr/sbin/daemon -u $iperf_user -p $iperf_pidfile -f $command"
load_rc_config $name
: ${iperf_enable="YES"}
run_rc_command "$1"
