PLUGIN_NAME=		collectd
PLUGIN_VERSION=		1.4
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Collect system and application performance metrics periodically
PLUGIN_DEPENDS=		collectd5
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
