PLUGIN_NAME=            collectd
PLUGIN_VERSION=         0.1
PLUGIN_COMMENT=         collectd agent
PLUGIN_DEPENDS=         collectd5
PLUGIN_MAINTAINER=      m.muenz@gmail.com
PLUGIN_DEVEL=           yes

.include "../../Mk/plugins.mk"
