PLUGIN_NAME=	        vep1400-hw	
PLUGIN_VERSION=		1.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=	        Dell EMC VEP1400 initialization scripts 	
PLUGIN_MAINTAINER=      brandontolbird@proton.me	
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
