[start]
command:/usr/local/etc/rc.d/softflowd start
parameters:
type:script
message:starting softflowd for Flowtriq

[stop]
command:/usr/local/etc/rc.d/softflowd stop; exit 0
parameters:
type:script
message:stopping softflowd for Flowtriq

[restart]
command:/usr/local/etc/rc.d/softflowd restart
parameters:
type:script
description:Restart Flowtriq NetFlow export
message:restarting softflowd for Flowtriq

[status]
command:/usr/local/etc/rc.d/softflowd status; exit 0
parameters:
type:script_output
message:requesting softflowd status

[test]
command:/usr/local/opnsense/scripts/OPNsense/Flowtriq/test_connection.sh
parameters:
type:script_output
message:testing Flowtriq agent connectivity
