PLUGIN_NAME=		dec-hw
PLUGIN_VERSION=		1.1
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		Deciso hardware specific information
PLUGIN_MAINTAINER=	stephan.de.wit@deciso.com
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
