PLUGIN_NAME=    	radsecproxy
PLUGIN_VERSION=     1.0.1
PLUGIN_COMMENT=     radsecproxy - a generic RADIUS proxy that provides both RADIUS UDP and TCP/TLS (RadSec) transport.
PLUGIN_DEPENDS=		radsecproxy
PLUGIN_MAINTAINER= 	tobias@boehnert.dev

.include "../../Mk/plugins.mk"
