PLUGIN_NAME=		radsecproxy
PLUGIN_VERSION=		0.0.1
PLUGIN_COMMENT=		radsecproxy - a generic RADIUS proxy that provides both RADIUS UDP and TCP/TLS (RadSec) transport.
PLUGIN_DEPENDS=		radsecproxy
PLUGIN_MAINTAINER=	tobias@boehnert.dev
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
