PLUGIN_NAME=		intrusion-detection-content-snort-vrt
PLUGIN_VERSION=		1.2
PLUGIN_COMMENT=		IDS Snort VRT ruleset (needs registration or subscription)
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_WWW=		https://www.snort.org/downloads#rules

.include "../../Mk/plugins.mk"
