PLUGIN_NAME=          antispam
PLUGIN_VERSION=       0.1
PLUGIN_COMMENT=       Package to configure postfix, rspamd and clamav to protect your network from Malware and Spam
PLUGIN_DEPENDS=       rspamd os-clamav postfix-sasl
PLUGIN_MAINTAINER=    franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
