PLUGIN_NAME=		theme-cicada
PLUGIN_VERSION=		0.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		The grey-orange theme
PLUGIN_MAINTAINER=	remic-webdesign@chello.at
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"