PLUGIN_NAME=		theme-cicada
PLUGIN_VERSION=		0.2
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		The cicada theme - grey/orange
PLUGIN_MAINTAINER=	remic-webdesign@chello.at
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
