PLUGIN_NAME=		theme-cicada
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		The cicada theme - grey/orange
PLUGIN_MAINTAINER=	remic-webdesign@chello.at
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
