PLUGIN_NAME=		c-icap
PLUGIN_VERSION=		1.7
PLUGIN_REVISION=	3
PLUGIN_COMMENT=		c-icap connects the web proxy with a virus scanner
PLUGIN_DEPENDS=		c-icap c-icap-modules
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
