PLUGIN_NAME=		c-icap
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		c-icap connects your Proxy with a virus scanner
PLUGIN_DEPENDS=		c-icap c-icap-modules
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
