PLUGIN_NAME=		c-icap
PLUGIN_VERSION=		1.4
PLUGIN_COMMENT=		c-icap connects your Proxy with a virus scanner
PLUGIN_DEPENDS=		c-icap c-icap-modules
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
