[lldp]
command:command -v lldpctl >/dev/null 2>&1 && lldpctl 2>/dev/null || true
type:script_output
description:Get LLDP neighbors
message:Getting LLDP neighbors
errors:no

[arp]
command:arp -an
type:script_output
description:Get ARP table
message:Getting ARP table
errors:no

[ndp]
command:ndp -an
type:script_output
description:Get NDP table
message:Getting NDP table
errors:no

[interfaces]
command:ifconfig -l
type:script_output
description:Get interface list
message:Getting interface list
errors:no
