PLUGIN_NAME=		intrusion-detection-content-et-pro
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		IDS Proofpoint ET Pro ruleset (needs a valid subscription)
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_WWW=		https://www.proofpoint.com/us/threat-insight/et-pro-ruleset

.include "../../Mk/plugins.mk"
