PLUGIN_NAME=		intrusion-detection-content-et-pro
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		IDS Proofpoint ET Pro ruleset (needs a valid subscription)
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_WWW=		https://www.proofpoint.com/us/threat-insight/et-pro-ruleset
PLUGIN_DEVEL=		yes

.include "../../Mk/plugins.mk"
