PLUGIN_NAME=		stunnel
PLUGIN_VERSION=		1.0.5
PLUGIN_REVISION=	3
PLUGIN_COMMENT=		Stunnel TLS proxy
PLUGIN_MAINTAINER=	ad@opnsense.org
PLUGIN_DEPENDS=		stunnel
PLUGIN_TIER=		2

.include "../../Mk/plugins.mk"
