#!/usr/local/bin/php
<?php

/*
 * Copyright (C) 2025 Myah Mitchell, Innovative Networks, Inc. d.b.a INDIGEX
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

require_once("config.inc");
require_once("util.inc");
require_once("plugins.inc.d/netbird.inc");

if (netbird_carp_enabled()) {
    $subsystem = !empty($argv[1]) ? $argv[1] : '';
    $type = !empty($argv[2]) ? $argv[2] : '';

    if ($type != 'MASTER' && $type != 'BACKUP') {
        log_msg("Carp '$type' event unknown from source '{$subsystem}'");
        exit(1);
    }

    if (!strstr($subsystem, '@')) {
        log_msg("Carp '$type' event triggered from wrong source '{$subsystem}'");
        exit(1);
    }

    // Lock file to ensure filter reload only runs once across all CARP events
    // (multiple interfaces transition simultaneously during failover)
    $lockfile_master = '/var/run/netbird.CARP_MASTER';
    $lockfile_backup = '/var/run/netbird.CARP_BACKUP';

    switch ($type) {
        case 'MASTER':
            // Only the first MASTER event creates the lock file and triggers the reload
            if (!file_exists($lockfile_master)) {
                @file_put_contents($lockfile_master, (string)getmypid());

                @unlink($lockfile_backup);
                $found_wt0 = false;

                log_msg("NetBird CARP: MASTER event from '{$subsystem}', starting NetBird's WireGuard interface");
                mwexecfm('/usr/local/bin/netbird up > /dev/null');
                for ($i = 0; $i < 10; $i++) {
                    sleep(1);
                    if (file_exists('/dev/wt0')) {
                        $found_wt0 = true;
                        break;
                    }
                }
                if ($found_wt0) {
                    log_msg("NetBird CARP: Found wt0 interface, reloading filter");
                    mwexecfm('/usr/local/sbin/configctl filter reload > /dev/null');
                }
                else {
                    log_msg("NetBird CARP: Timeout waiting for wt0 interface to appear after NetBird up. Filter reload skipped.");
                }
            } else {
                log_msg("NetBird CARP: Ignoring duplicate MASTER event from '{$subsystem}'");
            }
            break;
        case 'BACKUP':
            // Only the first BACKUP event creates the lock file and triggers the down
            if (!file_exists($lockfile_backup)) {
                @file_put_contents($lockfile_backup, (string)getmypid());

                @unlink($lockfile_master);

                log_msg("NetBird CARP: BACKUP event from '{$subsystem}', stopping NetBird's WireGuard interface");
                mwexecfm('/usr/local/bin/netbird down > /dev/null');
            } else {
                log_msg("NetBird CARP: Ignoring duplicate BACKUP event from '{$subsystem}'");
            }
            break;
    }
}
