PLUGIN_NAME=		proxy-sso
PLUGIN_VERSION=		1.3
PLUGIN_COMMENT=		Kerberos authentication module
PLUGIN_DEPENDS=		msktutil cyrus-sasl-gssapi
PLUGIN_MAINTAINER=	evbevz@gmail.com
PLUGIN_WWW=		http://smart-soft.ru

.include "../../Mk/plugins.mk"
