PLUGIN_NAME=		munin-node
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Munin monitorin agent
PLUGIN_DEPENDS=		munin-node
PLUGIN_DEVEL=		yes
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
