PLUGIN_NAME=        squidGuard
PLUGIN_VERSION=     0.1
PLUGIN_REVISION=    2-dev
PLUGIN_COMMENT=     squidGuard plugin
PLUGIN_DEPENDS=		squidGuard
PLUGIN_MAINTAINER=  jcamargo@cloudfence.com.br
PLUGIN_WWW=     https://www.cloudfence.com.br/

.include "../../Mk/plugins.mk"
