PLUGIN_NAME=		netbird
PLUGIN_VERSION=		0.8
PLUGIN_REVISION=	1
PLUGIN_DEPENDS=	    netbird
PLUGIN_COMMENT=		Netbird plugin
PLUGIN_MAINTAINER=	opn-netbird@sun-ri.se
PLUGIN_WWW=		    https:/netbird.io
PLUGIN_DEVEL=       no
PLUGIN_SUFFIX=
.include "../../Mk/plugins.mk"
