PLUGIN_NAME=		netbird
PLUGIN_VERSION=		0.1
PLUGIN_DEPENDS=	    netbird
PLUGIN_COMMENT=		Peer-to-peer VPN that seamlessly connects your devices
PLUGIN_MAINTAINER=	opn-netbird@sun-ri.se
PLUGIN_WWW=		    https://netbird.io
PLUGIN_DEVEL=       yes

.include "../../Mk/plugins.mk"