PLUGIN_NAME=		zabbix-proxy
PLUGIN_VERSION=		1.9
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		Zabbix monitoring proxy
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_VARIANTS=	zabbix6 zabbix62 zabbix64 zabbix5 zabbix4

zabbix64_NAME=		zabbix64-proxy
zabbix64_DEPENDS=	zabbix64-proxy

zabbix62_NAME=		zabbix62-proxy
zabbix62_DEPENDS=	zabbix62-proxy

zabbix6_NAME=		zabbix6-proxy
zabbix6_DEPENDS=	zabbix6-proxy

zabbix5_NAME=		zabbix5-proxy
zabbix5_DEPENDS=	zabbix5-proxy

zabbix4_NAME=		zabbix4-proxy
zabbix4_DEPENDS=	zabbix4-proxy

.include "../../Mk/plugins.mk"
