PLUGIN_NAME=		zabbix-proxy
PLUGIN_VERSION=		1.14
PLUGIN_COMMENT=		Zabbix monitoring proxy
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_VARIANTS=	zabbix7 zabbix72 zabbix74 zabbix6

zabbix7_NAME=		zabbix7-proxy
zabbix7_DEPENDS=	zabbix7-proxy

zabbix72_NAME=		zabbix72-proxy
zabbix72_DEPENDS=	zabbix72-proxy

zabbix74_NAME=		zabbix74-proxy
zabbix74_DEPENDS=	zabbix74-proxy

zabbix6_NAME=		zabbix6-proxy
zabbix6_DEPENDS=	zabbix6-proxy

.include "../../Mk/plugins.mk"
