PLUGIN_NAME=		zabbix-proxy
PLUGIN_VERSION=		1.12
PLUGIN_COMMENT=		Zabbix monitoring proxy
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_VARIANTS=	zabbix7 zabbix72 zabbix6 zabbix5

zabbix7_NAME=		zabbix7-proxy
zabbix7_DEPENDS=	zabbix7-proxy

zabbix72_NAME=		zabbix72-proxy
zabbix72_DEPENDS=	zabbix72-proxy

zabbix6_NAME=		zabbix6-proxy
zabbix6_DEPENDS=	zabbix6-proxy

zabbix5_NAME=		zabbix5-proxy
zabbix5_DEPENDS=	zabbix5-proxy

.include "../../Mk/plugins.mk"
