PLUGIN_NAME=          backup-api
PLUGIN_VERSION=       0.0.1
PLUGIN_COMMENT=       Provide the functionality to download the config.xml
PLUGIN_MAINTAINER=    franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
