info:
  description: API for managing your OPNsense firewall
  title: OPNsense API
  version: '25.1'
paths:
  captiveportal/accesscontroller/logon:
    post:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/accesscontroller/logoff:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/accesscontroller/status:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/accesscontroller/api:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/servicecontroller/reconfigure:
    post:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/servicecontroller/gettemplate:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/servicecontroller/savetemplate:
    post:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/servicecontroller/deltemplate:
    post:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/servicecontroller/searchtemplates:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/sessioncontroller/list:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/sessioncontroller/search:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/sessioncontroller/zones:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/sessioncontroller/disconnect:
    post:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/sessioncontroller/connect:
    post:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/settingscontroller/get:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/.opnsense.captiveportal.captiveportal'
  captiveportal/settingscontroller/set:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/.opnsense.captiveportal.captiveportal'
  captiveportal/settingscontroller/getzone:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/.opnsense.captiveportal.captiveportal'
  captiveportal/settingscontroller/setzone:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/.opnsense.captiveportal.captiveportal'
  captiveportal/settingscontroller/addzone:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/.opnsense.captiveportal.captiveportal'
  captiveportal/settingscontroller/delzone:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/.opnsense.captiveportal.captiveportal'
  captiveportal/settingscontroller/togglezone:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/.opnsense.captiveportal.captiveportal'
  captiveportal/settingscontroller/searchzones:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/.opnsense.captiveportal.captiveportal'
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/.opnsense.captiveportal.captiveportal'
  captiveportal/vouchercontroller/listproviders:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/vouchercontroller/listvouchergroups:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/vouchercontroller/listvouchers:
    get:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/vouchercontroller/dropvouchergroup:
    post:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/vouchercontroller/dropexpiredvouchers:
    post:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/vouchercontroller/generatevouchers:
    post:
      responses:
        '200':
          content:
            application/json: {}
  captiveportal/vouchercontroller/expirevoucher:
    post:
      responses:
        '200':
          content:
            application/json: {}
openapi: 3.0.0
components:
  schemas:
    opnsense.captiveportal.captiveportal:
      type: object
      properties:
        zones:
          type: object
          properties:
            zone:
              type: array
              items:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: '1'
                  zoneid:
                    type: integer
                    minimumvalue: '0'
                    maximumvalue: '19'
                    validationmessage: Maximum number of zones reached
                  interfaces:
                    type: array
                    items:
                      type: object
                      properties:
                        required:
                          type: object
                          properties: {}
                        multiple:
                          type: object
                          properties: {}
                        default:
                          type: object
                          properties: {}
                        filters:
                          type: object
                          properties:
                            enable:
                              type: object
                              properties: {}
                            ipaddr:
                              type: object
                              properties: {}
                        validationmessage:
                          type: object
                          properties: {}
                  interfaces_inbound:
                    type: array
                    items:
                      type: object
                      properties:
                        multiple:
                          type: object
                          properties: {}
                        filters:
                          type: object
                          properties:
                            enable:
                              type: object
                              properties: {}
                  authservers:
                    type: array
                    items:
                      type: object
                      properties:
                        multiple:
                          type: object
                          properties: {}
                  alwayssendaccountingreqs:
                    type: boolean
                    default: '0'
                  authenforcegroup:
                    type: array
                    items:
                      type: object
                      properties: {}
                  idletimeout:
                    type: integer
                    default: '0'
                    minimumvalue: '0'
                    maximumvalue: '10080'
                    validationmessage: Idle timeout, in minutes, must be between 0
                      (no timeout) and 10080 (a week)
                  hardtimeout:
                    type: integer
                    default: '0'
                    minimumvalue: '0'
                    maximumvalue: '10080'
                    validationmessage: Hard timeout, in minutes, must be between 0
                      (no timeout) and 10080 (a week)
                  concurrentlogins:
                    type: boolean
                    default: '1'
                  certificate:
                    type: array
                    items:
                      type: object
                      properties:
                        validationmessage:
                          type: object
                          properties: {}
                  servername:
                    type: string
                    mask: /^([0-9a-zA-Z.,_\-]){0,1024}$/u
                    validationmessage: Please enter a valid servername, ip address
                      or leave this option blank
                  allowedaddresses:
                    type: string
                    fieldseparator: ','
                    aslist: Y
                    wildcardenabled: N
                  allowedmacaddresses:
                    type: string
                    aslist: Y
                  extendedpreauthdata:
                    type: boolean
                    default: '0'
                  template:
                    type: array
                    items:
                      type: object
                      properties:
                        model:
                          type: object
                          properties:
                            template:
                              type: object
                              properties:
                                source:
                                  type: object
                                  properties: {}
                                items:
                                  type: object
                                  properties: {}
                                display:
                                  type: object
                                  properties: {}
                        validationmessage:
                          type: object
                          properties: {}
                  description:
                    type: string
                required:
                - enabled
                - zoneid
                - alwayssendaccountingreqs
                - idletimeout
                - hardtimeout
                - concurrentlogins
                - extendedpreauthdata
                - description
        templates:
          type: object
          properties:
            template:
              type: array
              items:
                type: object
                properties:
                  fileid:
                    type: string
                    mask: /[0-9a-zA-Z\-]{1,255}/u
                    validationmessage: Fileid should be an internally generated unique
                      number
                  name:
                    type: string
                    mask: /^([\t\n\v\f\r 0-9a-zA-Z.,_\x{00A0}-\x{FFFF}]){1,255}$/u
                    validationmessage: Template name should be a string between 1
                      and 255 characters
                  content:
                    type: string
                    mask: /[0-9a-zA-Z\+\=\/]{20,}/u
                    validationmessage: File content should be in (base64 encoded)
                      zip format
                required:
                - fileid
                - name
                - content
