info:
  description: API for managing your OPNsense firewall
  title: OPNsense API
  version: '25.1'
paths:
  auth/groupcontroller/get: {}
openapi: 3.0.0
components:
  schemas:
    auth.priv:
      type: object
      properties:
        users:
          type: array
          items:
            type: object
            properties:
              model:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      source:
                        type: object
                        properties: {}
                      items:
                        type: object
                        properties: {}
                      display:
                        type: object
                        properties: {}
              multiple:
                type: object
                properties: {}
        groups:
          type: array
          items:
            type: object
            properties:
              model:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      source:
                        type: object
                        properties: {}
                      items:
                        type: object
                        properties: {}
                      display:
                        type: object
                        properties: {}
              multiple:
                type: object
                properties: {}
