PLUGIN_NAME=		ntopng
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		Traffic Analysis and Flow Collection
PLUGIN_DEPENDS=		ntopng redis
PLUGIN_MAINTAINER=	m.muenz@gmail.com
PLUGIN_DEVEL=       yes

.include "../../Mk/plugins.mk"
