PLUGIN_NAME=		ntopng
PLUGIN_VERSION=		1.2
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		Traffic Analysis and Flow Collection
PLUGIN_DEPENDS=		ntopng
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
