[send]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/TelegramNotify/send_message.py
parameters:%s %s
type:script_output
description:Send a Telegram notification
message:Sending Telegram notification

[monit]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/TelegramNotify/monit_hook.py
parameters:%s %s %s %s %s %s
type:script_output
description:Send a Telegram notification from Monit event
message:Sending Telegram notification from Monit

[ids.poll]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/TelegramNotify/ids_poll.py
parameters:%s
type:script_output
description:Poll IDS alerts and send Telegram notifications
message:Polling IDS alerts for Telegram notifications

[monit.poll]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/TelegramNotify/monit_poll.py
parameters:%s
type:script_output
description:Poll Monit log alerts and send Telegram notifications
message:Polling Monit alerts for Telegram notifications
