[send]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/OPNsense/TelegramNotify/send_message.py
parameters:%s %s
type:script_output
description:Send a Telegram notification
message:Sending Telegram notification
