PLUGIN_NAME=        configsync
PLUGIN_VERSION=     0.1
PLUGIN_REVISION=    4
PLUGIN_COMMENT=     Sync OPNsense configurations to S3 compatible data storage
PLUGIN_MAINTAINER=  contact@verbnetworks.com
PLUGIN_WWW=         https://verbnetworks.com
PLUGIN_DEVEL=       no

.include "../../Mk/plugins.mk"
