PLUGIN_NAME=		pptp
PLUGIN_PRIVATE=		yes
PLUGIN_VERSION=		0.5
PLUGIN_REVISION=	1
PLUGIN_DEPENDS=		clog mpd5
PLUGIN_COMMENT=		PPTP server based on MPD5
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
