PLUGIN_NAME=		pptp
PLUGIN_VERSION=		1.7
PLUGIN_REVISION=	2
PLUGIN_DEPENDS=		clog mpd5
PLUGIN_COMMENT=		PPTP server based on MPD5
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
