PLUGIN_NAME=		upnp
PLUGIN_VERSION=		1.7
PLUGIN_REVISION=	1
PLUGIN_DEPENDS=		miniupnpd
PLUGIN_COMMENT=		Universal Plug and Play (UPnP IGD & PCP/NAT-PMP) Service
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
