PLUGIN_NAME=		upnp
PLUGIN_VERSION=		0.1
PLUGIN_PRIVATE=		yes
PLUGIN_DEPENDS=		miniupnpd
PLUGIN_COMMENT=		Universal Plug and Play Service
PLUGIN_MAINTAINER=	franco@opnsense.org

.include "../../Mk/plugins.mk"
