PLUGIN_NAME=		tailscale
PLUGIN_VERSION=		1.0.d
PLUGIN_DEVEL=		yes
PLUGIN_COMMENT=		VPN mesh securely connecting clients using WireGuard
PLUGIN_DEPENDS=		tailscale
PLUGIN_MAINTAINER=	sam@sheridan.co.uk

.include "../../Mk/plugins.mk"
