PLUGIN_NAME=       tailscale
PLUGIN_VERSION=    1.0
PLUGIN_REVISION=   1
PLUGIN_COMMENT=    Tailscale makes creating software-defined networks easy
PLUGIN_DEPENDS=    tailscale
PLUGIN_MAINTAINER= sam@sheridan.co.uk

.include "../../Mk/plugins.mk"
