PLUGIN_NAME=		tailscale
PLUGIN_VERSION=		1.4
PLUGIN_COMMENT=		VPN mesh securely connecting clients using WireGuard
PLUGIN_DEPENDS=		tailscale
PLUGIN_MAINTAINER=	sam@sheridan.uk

.include "../../Mk/plugins.mk"
